export const APIMock = [
    {
        tags: 3,
        bpp: 100,
        plnt: "Plant1",
        order_id: "ORD001",
        order_type: "Type1",
        line_code: "LITM001",
        item_desc: "Item Description 1",
        oq: 100,
        lead_time: 7,
        due_dt: "2024-08-15",
        cus_name: "Customer One",
        crdd: "2024-08-10",
        release_date: "2024-08-05",
        order_attr_1: "Attribute 1A",
        order_attr_2: "Attribute 1B",
        order_attr_3: "Attribute 1C"
    },
    {
        tags: 2,
        bpp: 100,
        plnt: "Plant2",
        order_id: "ORD002",
        order_type: "Type2",
        line_code: "LITM002",
        item_desc: "Item Description 2",
        oq: 150,
        lead_time: 10,
        due_dt: "2024-08-20",
        cus_name: "Customer Two",
        crdd: "2024-08-15",
        release_date: "2024-08-10",
        order_attr_1: "Attribute 2A",
        order_attr_2: "Attribute 2B",
        order_attr_3: "Attribute 2C"
    },
    {
        tags: 3,
        bpp: 100,
        plnt: "Plant3",
        order_id: "ORD003",
        order_type: "Type3",
        line_code: "LITM003",
        item_desc: "Item Description 3",
        oq: 200,
        lead_time: 12,
        due_dt: "2024-08-25",
        cus_name: "Customer Three",
        crdd: "2024-08-20",
        release_date: "2024-08-15",
        order_attr_1: "Attribute 3A",
        order_attr_2: "Attribute 3B",
        order_attr_3: "Attribute 3C"
    },
    {
        tags: 2,
        bpp: 100,
        plnt: "Plant4",
        order_id: "ORD004",
        order_type: "Type4",
        line_code: "LITM004",
        item_desc: "Item Description 4",
        oq: 250,
        lead_time: 15,
        due_dt: "2024-08-30",
        cus_name: "Customer Four",
        crdd: "2024-08-25",
        release_date: "2024-08-20",
        order_attr_1: "Attribute 4A",
        order_attr_2: "Attribute 4B",
        order_attr_3: "Attribute 4C"
    },
    {
        tags: 2,
        bpp: 100,
        plnt: "Plant5",
        order_id: "ORD005",
        order_type: "Type5",
        line_code: "LITM005",
        item_desc: "Item Description 5",
        oq: 300,
        lead_time: 18,
        due_dt: "2024-09-05",
        cus_name: "Customer Five",
        crdd: "2024-08-30",
        release_date: "2024-08-25",
        order_attr_1: "Attribute 5A",
        order_attr_2: "Attribute 5B",
        order_attr_3: "Attribute 5C"
    }
];



export const gridColumnConfig = [
    {
        cc: "tags",
        cp: 0,
        hd: "Tags",
        v: true,
        cla: "center",
        scc: "tags"
    },
    {
        cc: "bpp",
        cp: 1,
        hd: "BPP",
        v: true,
        cla: "center",
        scc: "bpp",
    },
    {
        cc: "plnt",
        cp: 2,
        hd: "Plant",
        v: true,
        cla: "center",
        scc: "plnt",
    },
    {
        cc: "order_id",
        cp: 3,
        hd: "Order ID",
        v: true,
        cla: "center",
        scc: "order_id",
    },
    {
        cc: "order_type",
        cp: 4,
        hd: "Order Type",
        v: true,
        cla: "center",
        scc: "order_type",
    },
    {
        cc: "line_code",
        cp: 5,
        hd: "Line Code",
        v: true,
        cla: "center",
        scc: "line_code",
    },
    {
        cc: "item_desc",
        cp: 6,
        hd: "Item Description",
        v: true,
        cla: "center",
        scc: "item_desc",
    },
    {
        cc: "oq",
        cp: 7,
        hd: "Order Quantity",
        v: true,
        cla: "center",
        scc: "oq",
    },
    {
        cc: "lead_time",
        cp: 8,
        hd: "Lead Time (In Days)",
        v: true,
        cla: "center",
        scc: "lead_time",
    },
    {
        cc: "due_dt",
        cp: 9,
        hd: "Due Date",
        v: true,
        cla: "center",
        scc: "due_dt",
    },
    {
        cc: "cus_name",
        cp: 10,
        hd: "Customer Name",
        v: true,
        cla: "center",
        scc: "cus_name",
    },
    {
        cc: "crdd",
        cp: 11,
        hd: "CRDD",
        v: true,
        cla: "center",
        scc: "crdd",
    },
    {
        cc: "release_date",
        cp: 12,
        hd: "Release Date",
        v: true,
        cla: "center",
        scc: "release_date",
    },
    {
        cc: "order_attr_1",
        cp: 13,
        hd: "Order Attribute 1",
        v: true,
        cla: "center",
        scc: "order_attr_1",
    },
    {
        cc: "order_attr_2",
        cp: 14,
        hd: "Order Attribute 2",
        v: true,
        cla: "center",
        scc: "order_attr_2",
    },
    {
        cc: "order_attr_3",
        cp: 15,
        hd: "Order Attribute 3",
        v: true,
        cla: "center",
        scc: "order_attr_3",
    }
];
