export const mockDBMData : any={
    
    "recordCount": null,
    "data": [
        {
            "RN": 1,
            "SKUCode": "AREB5092381",
            "SKUName": "SB2-NOTCH-KNIT-ZERO CALORIE-CORE",
            "LocCode": "2239",
            "LocName": "Annannagar|CHN",
            "OldNormValue": 1,
            "NewNormValue": 2,
            "Type": 10,
            "Comment": "Norm 1 Consumption based Increase",
            "PWhCode": "9020_EBO",
            "SKUAttribute1": "AREB5092",
            "SKUAttribute2": "38",
            "c3": "8.91E+12",
            "c4": "PC",
            "c5": "4999",
            "SKUAttribute6": "Arrow",
            "SKUAttribute7": "AR",
            "SKUAttribute8": "BZ",
            "SKUAttribute9": "CORE",
            "SKUAttribute10": "ZERO CALORIE",
            "c11": "Garment",
            "c12": "",
            "c13": "",
            "SKUAttribute14": "",
            "c15": "",
            "SkuLocAttribute1": "AREB5092",
            "SkuLocAttribute2": "38",
            "sl3": "AR",
            "sl4": "BZ",
            "sl5": "",
            "sl6": "",
            "sl7": "",
            "sl8": "",
            "sl9": "",
            "sl10": "AREB50922239",
            "sl11": "Yes",
            "sl12": "Nov-22",
            "sl13": "",
            "sl14": "",
            "sl15": "",
            "LocAttribute1": "EBO",
            "LocAttribute2": "10 to 15",
            "l3": "TN",
            "l4": "D-1",
            "l5": "NLTL",
            "l6": "SOUTH",
            "l7": "Tamil Nadu",
            "l8": "Chennai",
            "l9": "EC",
            "l10": "",
            "l11": "",
            "l12": "",
            "l13": "",
            "l14": "",
            "l15": ""
        },
        {
            "RN": 9,
            "SKUCode": "AREB5092401",
            "SKUName": "SB2-NOTCH-KNIT-ZERO CALORIE-CORE",
            "LocCode": "2016",
            "LocName": "Z Square|KPR",
            "OldNormValue": 2,
            "NewNormValue": 1,
            "Type": 11,
            "Comment": "Norm 2 Consumption based Decrease",
            "PWhCode": "9020_EBO",
            "SKUAttribute1": "AREB5092",
            "SKUAttribute2": "40",
            "c3": "8.91E+12",
            "c4": "PC",
            "c5": "4999",
            "SKUAttribute6": "Arrow",
            "SKUAttribute7": "AR",
            "SKUAttribute8": "BZ",
            "SKUAttribute9": "CORE",
            "SKUAttribute10": "ZERO CALORIE",
            "c11": "Garment",
            "c12": "",
            "c13": "",
            "SKUAttribute14": "",
            "c15": "",
            "SkuLocAttribute1": "AREB5092",
            "SkuLocAttribute2": "40",
            "sl3": "AR",
            "sl4": "BZ",
            "sl5": "",
            "sl6": "",
            "sl7": "",
            "sl8": "",
            "sl9": "",
            "sl10": "AREB50922016",
            "sl11": "Yes",
            "sl12": "Nov-22",
            "sl13": "",
            "sl14": "",
            "sl15": "",
            "LocAttribute1": "EBO",
            "LocAttribute2": "10 to 15",
            "l3": "UP/UK",
            "l4": "D-1",
            "l5": "LTL",
            "l6": "NORTH",
            "l7": "Uttar Pradesh",
            "l8": "Kanpur",
            "l9": "EC",
            "l10": "",
            "l11": "",
            "l12": "",
            "l13": "",
            "l14": "",
            "l15": ""
        },
        {
            "RN": 17,
            "SKUCode": "AREB5092401",
            "SKUName": "SB2-NOTCH-KNIT-ZERO CALORIE-CORE",
            "LocCode": "4339",
            "LocName": "New|Rourkela",
            "OldNormValue": 2,
            "NewNormValue": 1,
            "Type": 11,
            "Comment": "Norm 2 Consumption based Decrease",
            "PWhCode": "9020_EBO",
            "SKUAttribute1": "AREB5092",
            "SKUAttribute2": "40",
            "c3": "8.91E+12",
            "c4": "PC",
            "c5": "4999",
            "SKUAttribute6": "Arrow",
            "SKUAttribute7": "AR",
            "SKUAttribute8": "BZ",
            "SKUAttribute9": "CORE",
            "SKUAttribute10": "ZERO CALORIE",
            "c11": "Garment",
            "c12": "",
            "c13": "",
            "SKUAttribute14": "",
            "c15": "",
            "SkuLocAttribute1": "AREB5092",
            "SkuLocAttribute2": "40",
            "sl3": "AR",
            "sl4": "BZ",
            "sl5": "",
            "sl6": "",
            "sl7": "",
            "sl8": "",
            "sl9": "",
            "sl10": "",
            "sl11": "",
            "sl12": "06-09-2023",
            "sl13": "",
            "sl14": "",
            "sl15": "",
            "LocAttribute1": "EBO",
            "LocAttribute2": "10 to 15",
            "l3": "WB/OD",
            "l4": "New-B",
            "l5": "",
            "l6": "East",
            "l7": "Odisha",
            "l8": "Sundargarh",
            "l9": "EC",
            "l10": "Yes",
            "l11": "",
            "l12": "",
            "l13": "",
            "l14": "",
            "l15": ""
        },
        {
            "RN": 25,
            "SKUCode": "AREB5092421",
            "SKUName": "SB2-NOTCH-KNIT-ZERO CALORIE-CORE",
            "LocCode": "4144",
            "LocName": "Sec-17|CHD",
            "OldNormValue": 2,
            "NewNormValue": 1,
            "Type": 11,
            "Comment": "Norm 2 Consumption based Decrease",
            "PWhCode": "9020_EBO",
            "SKUAttribute1": "AREB5092",
            "SKUAttribute2": "42",
            "c3": "8.91E+12",
            "c4": "PC",
            "c5": "4999",
            "SKUAttribute6": "Arrow",
            "SKUAttribute7": "AR",
            "SKUAttribute8": "BZ",
            "SKUAttribute9": "CORE",
            "SKUAttribute10": "ZERO CALORIE",
            "c11": "Garment",
            "c12": "",
            "c13": "",
            "SKUAttribute14": "",
            "c15": "",
            "SkuLocAttribute1": "AREB5092",
            "SkuLocAttribute2": "42",
            "sl3": "AR",
            "sl4": "BZ",
            "sl5": "",
            "sl6": "",
            "sl7": "",
            "sl8": "",
            "sl9": "",
            "sl10": "AREB50924144",
            "sl11": "Yes",
            "sl12": "Jan-23",
            "sl13": "",
            "sl14": "",
            "sl15": "",
            "LocAttribute1": "EBO",
            "LocAttribute2": "25 to 30",
            "l3": "Punjab",
            "l4": "D-36",
            "l5": "LTL",
            "l6": "NORTH",
            "l7": "Chandigarh",
            "l8": "Chandigarh",
            "l9": "EC",
            "l10": "",
            "l11": "",
            "l12": "",
            "l13": "",
            "l14": "",
            "l15": ""
        },
        {
            "RN": 2,
            "SKUCode": "AREB5092381",
            "SKUName": "SB2-NOTCH-KNIT-ZERO CALORIE-CORE",
            "LocCode": "3882",
            "LocName": "Vegas|Dwarka",
            "OldNormValue": 1,
            "NewNormValue": 2,
            "Type": 10,
            "Comment": "Norm 1 Consumption based Increase",
            "PWhCode": "9020_EBO",
            "SKUAttribute1": "AREB5092",
            "SKUAttribute2": "38",
            "c3": "8.91E+12",
            "c4": "PC",
            "c5": "4999",
            "SKUAttribute6": "Arrow",
            "SKUAttribute7": "AR",
            "SKUAttribute8": "BZ",
            "SKUAttribute9": "CORE",
            "SKUAttribute10": "ZERO CALORIE",
            "c11": "Garment",
            "c12": "",
            "c13": "",
            "SKUAttribute14": "",
            "c15": "",
            "SkuLocAttribute1": "AREB5092",
            "SkuLocAttribute2": "38",
            "sl3": "AR",
            "sl4": "BZ",
            "sl5": "",
            "sl6": "",
            "sl7": "",
            "sl8": "",
            "sl9": "",
            "sl10": "AREB50923882",
            "sl11": "Yes",
            "sl12": "Nov-22",
            "sl13": "",
            "sl14": "",
            "sl15": "",
            "LocAttribute1": "EBO",
            "LocAttribute2": "10 to 15",
            "l3": "NCR",
            "l4": "D-1",
            "l5": "NLTL",
            "l6": "NORTH",
            "l7": "Delhi",
            "l8": "Delhi",
            "l9": "EC",
            "l10": "",
            "l11": "",
            "l12": "",
            "l13": "",
            "l14": "",
            "l15": ""
        },
        {
            "RN": 10,
            "SKUCode": "AREB5092401",
            "SKUName": "SB2-NOTCH-KNIT-ZERO CALORIE-CORE",
            "LocCode": "2046",
            "LocName": "Inorbit Vashi|MUM",
            "OldNormValue": 1,
            "NewNormValue": 2,
            "Type": 10,
            "Comment": "Norm 1 Consumption based Increase",
            "PWhCode": "9020_EBO",
            "SKUAttribute1": "AREB5092",
            "SKUAttribute2": "40",
            "c3": "8.91E+12",
            "c4": "PC",
            "c5": "4999",
            "SKUAttribute6": "Arrow",
            "SKUAttribute7": "AR",
            "SKUAttribute8": "BZ",
            "SKUAttribute9": "CORE",
            "SKUAttribute10": "ZERO CALORIE",
            "c11": "Garment",
            "c12": "",
            "c13": "",
            "SKUAttribute14": "",
            "c15": "",
            "SkuLocAttribute1": "AREB5092",
            "SkuLocAttribute2": "40",
            "sl3": "AR",
            "sl4": "BZ",
            "sl5": "",
            "sl6": "",
            "sl7": "",
            "sl8": "",
            "sl9": "",
            "sl10": "AREB50922046",
            "sl11": "Yes",
            "sl12": "Nov-22",
            "sl13": "",
            "sl14": "",
            "sl15": "",
            "LocAttribute1": "EBO",
            "LocAttribute2": "10 to 15",
            "l3": "MUM",
            "l4": "D-1",
            "l5": "NLTL",
            "l6": "WEST",
            "l7": "Maharashtra",
            "l8": "Mumbai",
            "l9": "EC",
            "l10": "",
            "l11": "",
            "l12": "",
            "l13": "",
            "l14": "",
            "l15": ""
        },
        {
            "RN": 18,
            "SKUCode": "AREB5092401",
            "SKUName": "SB2-NOTCH-KNIT-ZERO CALORIE-CORE",
            "LocCode": "4341",
            "LocName": "Mall Of Ranchi|Ranchi",
            "OldNormValue": 2,
            "NewNormValue": 1,
            "Type": 11,
            "Comment": "Norm 2 Consumption based Decrease",
            "PWhCode": "9020_EBO",
            "SKUAttribute1": "AREB5092",
            "SKUAttribute2": "40",
            "c3": "8.91E+12",
            "c4": "PC",
            "c5": "4999",
            "SKUAttribute6": "Arrow",
            "SKUAttribute7": "AR",
            "SKUAttribute8": "BZ",
            "SKUAttribute9": "CORE",
            "SKUAttribute10": "ZERO CALORIE",
            "c11": "Garment",
            "c12": "",
            "c13": "",
            "SKUAttribute14": "",
            "c15": "",
            "SkuLocAttribute1": "AREB5092",
            "SkuLocAttribute2": "40",
            "sl3": "AR",
            "sl4": "BZ",
            "sl5": "",
            "sl6": "",
            "sl7": "",
            "sl8": "",
            "sl9": "",
            "sl10": "",
            "sl11": "",
            "sl12": "06-09-2023",
            "sl13": "",
            "sl14": "",
            "sl15": "",
            "LocAttribute1": "EBO",
            "LocAttribute2": "10 to 15",
            "l3": "BR/JH",
            "l4": "NOT",
            "l5": "",
            "l6": "East",
            "l7": "Jharkhand",
            "l8": "Ranchi",
            "l9": "EC",
            "l10": "Yes",
            "l11": "",
            "l12": "",
            "l13": "",
            "l14": "",
            "l15": ""
        },
        {
            "RN": 26,
            "SKUCode": "AREB5092421",
            "SKUName": "SB2-NOTCH-KNIT-ZERO CALORIE-CORE",
            "LocCode": "4238",
            "LocName": "Sec11|Dwarka",
            "OldNormValue": 2,
            "NewNormValue": 1,
            "Type": 11,
            "Comment": "Norm 2 Consumption based Decrease",
            "PWhCode": "9020_EBO",
            "SKUAttribute1": "AREB5092",
            "SKUAttribute2": "42",
            "c3": "8.91E+12",
            "c4": "PC",
            "c5": "4999",
            "SKUAttribute6": "Arrow",
            "SKUAttribute7": "AR",
            "SKUAttribute8": "BZ",
            "SKUAttribute9": "CORE",
            "SKUAttribute10": "ZERO CALORIE",
            "c11": "Garment",
            "c12": "",
            "c13": "",
            "SKUAttribute14": "",
            "c15": "",
            "SkuLocAttribute1": "AREB5092",
            "SkuLocAttribute2": "42",
            "sl3": "AR",
            "sl4": "BZ",
            "sl5": "",
            "sl6": "",
            "sl7": "",
            "sl8": "",
            "sl9": "",
            "sl10": "AREB50924238",
            "sl11": "Yes",
            "sl12": "Nov-22",
            "sl13": "",
            "sl14": "",
            "sl15": "",
            "LocAttribute1": "EBO",
            "LocAttribute2": "10 to 15",
            "l3": "NCR",
            "l4": "D-2",
            "l5": "New",
            "l6": "North",
            "l7": "New Delhi",
            "l8": "New Delhi",
            "l9": "EC",
            "l10": "Yes",
            "l11": "",
            "l12": "",
            "l13": "",
            "l14": "",
            "l15": ""
        },
        {
            "RN": 3,
            "SKUCode": "AREB5092381",
            "SKUName": "SB2-NOTCH-KNIT-ZERO CALORIE-CORE",
            "LocCode": "4144",
            "LocName": "Sec-17|CHD",
            "OldNormValue": 2,
            "NewNormValue": 1,
            "Type": 11,
            "Comment": "Norm 2 Consumption based Decrease",
            "PWhCode": "9020_EBO",
            "SKUAttribute1": "AREB5092",
            "SKUAttribute2": "38",
            "c3": "8.91E+12",
            "c4": "PC",
            "c5": "4999",
            "SKUAttribute6": "Arrow",
            "SKUAttribute7": "AR",
            "SKUAttribute8": "BZ",
            "SKUAttribute9": "CORE",
            "SKUAttribute10": "ZERO CALORIE",
            "c11": "Garment",
            "c12": "",
            "c13": "",
            "SKUAttribute14": "",
            "c15": "",
            "SkuLocAttribute1": "AREB5092",
            "SkuLocAttribute2": "38",
            "sl3": "AR",
            "sl4": "BZ",
            "sl5": "",
            "sl6": "",
            "sl7": "",
            "sl8": "",
            "sl9": "",
            "sl10": "AREB50924144",
            "sl11": "Yes",
            "sl12": "Jan-23",
            "sl13": "",
            "sl14": "",
            "sl15": "",
            "LocAttribute1": "EBO",
            "LocAttribute2": "25 to 30",
            "l3": "Punjab",
            "l4": "D-36",
            "l5": "LTL",
            "l6": "NORTH",
            "l7": "Chandigarh",
            "l8": "Chandigarh",
            "l9": "EC",
            "l10": "",
            "l11": "",
            "l12": "",
            "l13": "",
            "l14": "",
            "l15": ""
        },
        {
            "RN": 11,
            "SKUCode": "AREB5092401",
            "SKUName": "SB2-NOTCH-KNIT-ZERO CALORIE-CORE",
            "LocCode": "2078",
            "LocName": "Alkapuri|Baroda",
            "OldNormValue": 1,
            "NewNormValue": 2,
            "Type": 10,
            "Comment": "Norm 1 Consumption based Increase",
            "PWhCode": "9020_EBO",
            "SKUAttribute1": "AREB5092",
            "SKUAttribute2": "40",
            "c3": "8.91E+12",
            "c4": "PC",
            "c5": "4999",
            "SKUAttribute6": "Arrow",
            "SKUAttribute7": "AR",
            "SKUAttribute8": "BZ",
            "SKUAttribute9": "CORE",
            "SKUAttribute10": "ZERO CALORIE",
            "c11": "Garment",
            "c12": "",
            "c13": "",
            "SKUAttribute14": "",
            "c15": "",
            "SkuLocAttribute1": "AREB5092",
            "SkuLocAttribute2": "40",
            "sl3": "AR",
            "sl4": "BZ",
            "sl5": "",
            "sl6": "",
            "sl7": "",
            "sl8": "",
            "sl9": "",
            "sl10": "AREB50922078",
            "sl11": "Yes",
            "sl12": "Nov-22",
            "sl13": "",
            "sl14": "",
            "sl15": "",
            "LocAttribute1": "EBO",
            "LocAttribute2": "20 to 25",
            "l3": "GUJ",
            "l4": "D-36",
            "l5": "LTL",
            "l6": "WEST",
            "l7": "Gujarat",
            "l8": "Vadodara",
            "l9": "EC",
            "l10": "",
            "l11": "",
            "l12": "",
            "l13": "",
            "l14": "",
            "l15": ""
        },
        {
            "RN": 19,
            "SKUCode": "AREB5092421",
            "SKUName": "SB2-NOTCH-KNIT-ZERO CALORIE-CORE",
            "LocCode": "2006",
            "LocName": "Khayala|DEL",
            "OldNormValue": 1,
            "NewNormValue": 2,
            "Type": 10,
            "Comment": "Norm 1 Consumption based Increase",
            "PWhCode": "9020_EBO",
            "SKUAttribute1": "AREB5092",
            "SKUAttribute2": "42",
            "c3": "8.91E+12",
            "c4": "PC",
            "c5": "4999",
            "SKUAttribute6": "Arrow",
            "SKUAttribute7": "AR",
            "SKUAttribute8": "BZ",
            "SKUAttribute9": "CORE",
            "SKUAttribute10": "ZERO CALORIE",
            "c11": "Garment",
            "c12": "",
            "c13": "",
            "SKUAttribute14": "",
            "c15": "",
            "SkuLocAttribute1": "AREB5092",
            "SkuLocAttribute2": "42",
            "sl3": "AR",
            "sl4": "BZ",
            "sl5": "",
            "sl6": "",
            "sl7": "",
            "sl8": "",
            "sl9": "",
            "sl10": "AREB50922006",
            "sl11": "Yes",
            "sl12": "Nov-22",
            "sl13": "",
            "sl14": "",
            "sl15": "",
            "LocAttribute1": "EBO",
            "LocAttribute2": "20 to 25",
            "l3": "NCR",
            "l4": "D-36",
            "l5": "LTL",
            "l6": "NORTH",
            "l7": "Delhi",
            "l8": "Delhi",
            "l9": "EC",
            "l10": "",
            "l11": "",
            "l12": "",
            "l13": "",
            "l14": "",
            "l15": ""
        },
        {
            "RN": 27,
            "SKUCode": "AREB5092421",
            "SKUName": "SB2-NOTCH-KNIT-ZERO CALORIE-CORE",
            "LocCode": "4319",
            "LocName": "Fun Mall|LKO",
            "OldNormValue": 2,
            "NewNormValue": 1,
            "Type": 11,
            "Comment": "Norm 2 Consumption based Decrease",
            "PWhCode": "9020_EBO",
            "SKUAttribute1": "AREB5092",
            "SKUAttribute2": "42",
            "c3": "8.91E+12",
            "c4": "PC",
            "c5": "4999",
            "SKUAttribute6": "Arrow",
            "SKUAttribute7": "AR",
            "SKUAttribute8": "BZ",
            "SKUAttribute9": "CORE",
            "SKUAttribute10": "ZERO CALORIE",
            "c11": "Garment",
            "c12": "",
            "c13": "",
            "SKUAttribute14": "",
            "c15": "",
            "SkuLocAttribute1": "AREB5092",
            "SkuLocAttribute2": "42",
            "sl3": "AR",
            "sl4": "BZ",
            "sl5": "",
            "sl6": "",
            "sl7": "",
            "sl8": "",
            "sl9": "",
            "sl10": "AREB50924319",
            "sl11": "Yes",
            "sl12": "Mar-23",
            "sl13": "",
            "sl14": "",
            "sl15": "",
            "LocAttribute1": "EBO",
            "LocAttribute2": "20 to 25",
            "l3": "UP/UK",
            "l4": "New-A",
            "l5": "New",
            "l6": "North",
            "l7": "Uttar Pradesh",
            "l8": "Lucknow",
            "l9": "EC",
            "l10": "Yes",
            "l11": "",
            "l12": "",
            "l13": "",
            "l14": "",
            "l15": ""
        },
        {
            "RN": 4,
            "SKUCode": "AREB5092381",
            "SKUName": "SB2-NOTCH-KNIT-ZERO CALORIE-CORE",
            "LocCode": "4182",
            "LocName": "Commercial St|BLR",
            "OldNormValue": 1,
            "NewNormValue": 2,
            "Type": 10,
            "Comment": "Norm 1 Consumption based Increase",
            "PWhCode": "9020_EBO",
            "SKUAttribute1": "AREB5092",
            "SKUAttribute2": "38",
            "c3": "8.91E+12",
            "c4": "PC",
            "c5": "4999",
            "SKUAttribute6": "Arrow",
            "SKUAttribute7": "AR",
            "SKUAttribute8": "BZ",
            "SKUAttribute9": "CORE",
            "SKUAttribute10": "ZERO CALORIE",
            "c11": "Garment",
            "c12": "",
            "c13": "",
            "SKUAttribute14": "",
            "c15": "",
            "SkuLocAttribute1": "AREB5092",
            "SkuLocAttribute2": "38",
            "sl3": "AR",
            "sl4": "BZ",
            "sl5": "",
            "sl6": "",
            "sl7": "",
            "sl8": "",
            "sl9": "",
            "sl10": "AREB50924182",
            "sl11": "Yes",
            "sl12": "Jan-23",
            "sl13": "",
            "sl14": "",
            "sl15": "",
            "LocAttribute1": "EBO",
            "LocAttribute2": "25 to 30",
            "l3": "KAR",
            "l4": "D-36",
            "l5": "NEW OPENED",
            "l6": "SOUTH",
            "l7": "Karnataka",
            "l8": "Benguluru",
            "l9": "EC",
            "l10": "",
            "l11": "",
            "l12": "",
            "l13": "",
            "l14": "",
            "l15": ""
        },
        {
            "RN": 12,
            "SKUCode": "AREB5092401",
            "SKUName": "SB2-NOTCH-KNIT-ZERO CALORIE-CORE",
            "LocCode": "2163",
            "LocName": "Punjagutta|HYD",
            "OldNormValue": 3,
            "NewNormValue": 2,
            "Type": 5,
            "Comment": "Buffer penetration has consistently been green. Downward revision suggested.",
            "PWhCode": "9020_EBO",
            "SKUAttribute1": "AREB5092",
            "SKUAttribute2": "40",
            "c3": "8.91E+12",
            "c4": "PC",
            "c5": "4999",
            "SKUAttribute6": "Arrow",
            "SKUAttribute7": "AR",
            "SKUAttribute8": "BZ",
            "SKUAttribute9": "CORE",
            "SKUAttribute10": "ZERO CALORIE",
            "c11": "Garment",
            "c12": "",
            "c13": "",
            "SKUAttribute14": "",
            "c15": "",
            "SkuLocAttribute1": "AREB5092",
            "SkuLocAttribute2": "40",
            "sl3": "AR",
            "sl4": "BZ",
            "sl5": "",
            "sl6": "",
            "sl7": "",
            "sl8": "",
            "sl9": "",
            "sl10": "AREB50922163",
            "sl11": "Yes",
            "sl12": "Nov-22",
            "sl13": "",
            "sl14": "",
            "sl15": "",
            "LocAttribute1": "EBO",
            "LocAttribute2": "5 to 10",
            "l3": "AP/TS",
            "l4": "D-2",
            "l5": "LTL",
            "l6": "SOUTH",
            "l7": "Ap/Tl",
            "l8": "Hyderabad",
            "l9": "EC",
            "l10": "",
            "l11": "",
            "l12": "",
            "l13": "",
            "l14": "",
            "l15": ""
        },
        {
            "RN": 20,
            "SKUCode": "AREB5092421",
            "SKUName": "SB2-NOTCH-KNIT-ZERO CALORIE-CORE",
            "LocCode": "2019",
            "LocName": "Colaba|MUM",
            "OldNormValue": 2,
            "NewNormValue": 1,
            "Type": 11,
            "Comment": "Norm 2 Consumption based Decrease",
            "PWhCode": "9020_EBO",
            "SKUAttribute1": "AREB5092",
            "SKUAttribute2": "42",
            "c3": "8.91E+12",
            "c4": "PC",
            "c5": "4999",
            "SKUAttribute6": "Arrow",
            "SKUAttribute7": "AR",
            "SKUAttribute8": "BZ",
            "SKUAttribute9": "CORE",
            "SKUAttribute10": "ZERO CALORIE",
            "c11": "Garment",
            "c12": "",
            "c13": "",
            "SKUAttribute14": "",
            "c15": "",
            "SkuLocAttribute1": "AREB5092",
            "SkuLocAttribute2": "42",
            "sl3": "AR",
            "sl4": "BZ",
            "sl5": "",
            "sl6": "",
            "sl7": "",
            "sl8": "",
            "sl9": "",
            "sl10": "AREB50922019",
            "sl11": "Yes",
            "sl12": "Nov-22",
            "sl13": "",
            "sl14": "",
            "sl15": "",
            "LocAttribute1": "EBO",
            "LocAttribute2": "15 to 20",
            "l3": "MUM",
            "l4": "D-1",
            "l5": "LTL",
            "l6": "WEST",
            "l7": "Maharashtra",
            "l8": "Mumbai",
            "l9": "EC",
            "l10": "",
            "l11": "",
            "l12": "",
            "l13": "",
            "l14": "",
            "l15": ""
        },
        {
            "RN": 28,
            "SKUCode": "AREB5092421",
            "SKUName": "SB2-NOTCH-KNIT-ZERO CALORIE-CORE",
            "LocCode": "4333",
            "LocName": "Rajkot|Twin Star",
            "OldNormValue": 2,
            "NewNormValue": 1,
            "Type": 11,
            "Comment": "Norm 2 Consumption based Decrease",
            "PWhCode": "9020_EBO",
            "SKUAttribute1": "AREB5092",
            "SKUAttribute2": "42",
            "c3": "8.91E+12",
            "c4": "PC",
            "c5": "4999",
            "SKUAttribute6": "Arrow",
            "SKUAttribute7": "AR",
            "SKUAttribute8": "BZ",
            "SKUAttribute9": "CORE",
            "SKUAttribute10": "ZERO CALORIE",
            "c11": "Garment",
            "c12": "",
            "c13": "",
            "SKUAttribute14": "",
            "c15": "",
            "SkuLocAttribute1": "AREB5092",
            "SkuLocAttribute2": "42",
            "sl3": "AR",
            "sl4": "BZ",
            "sl5": "",
            "sl6": "",
            "sl7": "",
            "sl8": "",
            "sl9": "",
            "sl10": "AREB50924333",
            "sl11": "Yes",
            "sl12": "Jul-23",
            "sl13": "",
            "sl14": "",
            "sl15": "",
            "LocAttribute1": "EBO",
            "LocAttribute2": "10 to 15",
            "l3": "GUJ",
            "l4": "New-A",
            "l5": "",
            "l6": "West",
            "l7": "Gujarat",
            "l8": "Rajkot",
            "l9": "EC",
            "l10": "Yes",
            "l11": "",
            "l12": "",
            "l13": "",
            "l14": "",
            "l15": ""
        },
        {
            "RN": 7,
            "SKUCode": "AREB5092381",
            "SKUName": "SB2-NOTCH-KNIT-ZERO CALORIE-CORE",
            "LocCode": "4341",
            "LocName": "Mall Of Ranchi|Ranchi",
            "OldNormValue": 2,
            "NewNormValue": 1,
            "Type": 11,
            "Comment": "Norm 2 Consumption based Decrease",
            "PWhCode": "9020_EBO",
            "SKUAttribute1": "AREB5092",
            "SKUAttribute2": "38",
            "c3": "8.91E+12",
            "c4": "PC",
            "c5": "4999",
            "SKUAttribute6": "Arrow",
            "SKUAttribute7": "AR",
            "SKUAttribute8": "BZ",
            "SKUAttribute9": "CORE",
            "SKUAttribute10": "ZERO CALORIE",
            "c11": "Garment",
            "c12": "",
            "c13": "",
            "SKUAttribute14": "",
            "c15": "",
            "SkuLocAttribute1": "AREB5092",
            "SkuLocAttribute2": "38",
            "sl3": "AR",
            "sl4": "BZ",
            "sl5": "",
            "sl6": "",
            "sl7": "",
            "sl8": "",
            "sl9": "",
            "sl10": "",
            "sl11": "",
            "sl12": "06-09-2023",
            "sl13": "",
            "sl14": "",
            "sl15": "",
            "LocAttribute1": "EBO",
            "LocAttribute2": "10 to 15",
            "l3": "BR/JH",
            "l4": "NOT",
            "l5": "",
            "l6": "East",
            "l7": "Jharkhand",
            "l8": "Ranchi",
            "l9": "EC",
            "l10": "Yes",
            "l11": "",
            "l12": "",
            "l13": "",
            "l14": "",
            "l15": ""
        },
        {
            "RN": 15,
            "SKUCode": "AREB5092401",
            "SKUName": "SB2-NOTCH-KNIT-ZERO CALORIE-CORE",
            "LocCode": "4179",
            "LocName": "Gorakhpur",
            "OldNormValue": 1,
            "NewNormValue": 2,
            "Type": 10,
            "Comment": "Norm 1 Consumption based Increase",
            "PWhCode": "9020_EBO",
            "SKUAttribute1": "AREB5092",
            "SKUAttribute2": "40",
            "c3": "8.91E+12",
            "c4": "PC",
            "c5": "4999",
            "SKUAttribute6": "Arrow",
            "SKUAttribute7": "AR",
            "SKUAttribute8": "BZ",
            "SKUAttribute9": "CORE",
            "SKUAttribute10": "ZERO CALORIE",
            "c11": "Garment",
            "c12": "",
            "c13": "",
            "SKUAttribute14": "",
            "c15": "",
            "SkuLocAttribute1": "AREB5092",
            "SkuLocAttribute2": "40",
            "sl3": "AR",
            "sl4": "BZ",
            "sl5": "",
            "sl6": "",
            "sl7": "",
            "sl8": "",
            "sl9": "",
            "sl10": "AREB50924179",
            "sl11": "Yes",
            "sl12": "Jan-23",
            "sl13": "",
            "sl14": "",
            "sl15": "",
            "LocAttribute1": "EBO",
            "LocAttribute2": "10 to 15",
            "l3": "UP/UK",
            "l4": "D-1",
            "l5": "NEW OPENED",
            "l6": "NORTH",
            "l7": "Uttar Pradesh",
            "l8": "Gorakpur",
            "l9": "EC",
            "l10": "",
            "l11": "",
            "l12": "",
            "l13": "",
            "l14": "",
            "l15": ""
        },
        {
            "RN": 23,
            "SKUCode": "AREB5092421",
            "SKUName": "SB2-NOTCH-KNIT-ZERO CALORIE-CORE",
            "LocCode": "4032",
            "LocName": "JM Rd.|Pune",
            "OldNormValue": 2,
            "NewNormValue": 1,
            "Type": 11,
            "Comment": "Norm 2 Consumption based Decrease",
            "PWhCode": "9020_EBO",
            "SKUAttribute1": "AREB5092",
            "SKUAttribute2": "42",
            "c3": "8.91E+12",
            "c4": "PC",
            "c5": "4999",
            "SKUAttribute6": "Arrow",
            "SKUAttribute7": "AR",
            "SKUAttribute8": "BZ",
            "SKUAttribute9": "CORE",
            "SKUAttribute10": "ZERO CALORIE",
            "c11": "Garment",
            "c12": "",
            "c13": "",
            "SKUAttribute14": "",
            "c15": "",
            "SkuLocAttribute1": "AREB5092",
            "SkuLocAttribute2": "42",
            "sl3": "AR",
            "sl4": "BZ",
            "sl5": "",
            "sl6": "",
            "sl7": "",
            "sl8": "",
            "sl9": "",
            "sl10": "AREB50924032",
            "sl11": "Yes",
            "sl12": "Nov-22",
            "sl13": "",
            "sl14": "",
            "sl15": "",
            "LocAttribute1": "EBO",
            "LocAttribute2": "20 to 25",
            "l3": "MH",
            "l4": "D-36",
            "l5": "NEW OPENED",
            "l6": "WEST",
            "l7": "Maharashtra",
            "l8": "Pune",
            "l9": "EC",
            "l10": "",
            "l11": "",
            "l12": "",
            "l13": "",
            "l14": "",
            "l15": ""
        },
        {
            "RN": 31,
            "SKUCode": "AREB5093361",
            "SKUName": "SB2-NOTCH-KNIT-ZERO CALORIE-CORE",
            "LocCode": "4034",
            "LocName": "Alpha|AHM",
            "OldNormValue": 2,
            "NewNormValue": 1,
            "Type": 11,
            "Comment": "Norm 2 Consumption based Decrease",
            "PWhCode": "9020_EBO",
            "SKUAttribute1": "AREB5093",
            "SKUAttribute2": "36",
            "c3": "8.91E+12",
            "c4": "PC",
            "c5": "4999",
            "SKUAttribute6": "Arrow",
            "SKUAttribute7": "AR",
            "SKUAttribute8": "BZ",
            "SKUAttribute9": "CORE",
            "SKUAttribute10": "ZERO CALORIE",
            "c11": "Garment",
            "c12": "",
            "c13": "",
            "SKUAttribute14": "",
            "c15": "",
            "SkuLocAttribute1": "AREB5093",
            "SkuLocAttribute2": "36",
            "sl3": "AR",
            "sl4": "BZ",
            "sl5": "",
            "sl6": "",
            "sl7": "",
            "sl8": "",
            "sl9": "",
            "sl10": "AREB50934034",
            "sl11": "Yes",
            "sl12": "Nov-22",
            "sl13": "",
            "sl14": "",
            "sl15": "",
            "LocAttribute1": "EBO",
            "LocAttribute2": "30 to 35",
            "l3": "GUJ",
            "l4": "D-36",
            "l5": "LTL",
            "l6": "WEST",
            "l7": "Gujarat",
            "l8": "Ahmedabad",
            "l9": "EC",
            "l10": "",
            "l11": "",
            "l12": "",
            "l13": "",
            "l14": "",
            "l15": ""
        },
        {
            "RN": 5,
            "SKUCode": "AREB5092381",
            "SKUName": "SB2-NOTCH-KNIT-ZERO CALORIE-CORE",
            "LocCode": "4241",
            "LocName": "Shipra|GHZ",
            "OldNormValue": 2,
            "NewNormValue": 1,
            "Type": 11,
            "Comment": "Norm 2 Consumption based Decrease",
            "PWhCode": "9020_EBO",
            "SKUAttribute1": "AREB5092",
            "SKUAttribute2": "38",
            "c3": "8.91E+12",
            "c4": "PC",
            "c5": "4999",
            "SKUAttribute6": "Arrow",
            "SKUAttribute7": "AR",
            "SKUAttribute8": "BZ",
            "SKUAttribute9": "CORE",
            "SKUAttribute10": "ZERO CALORIE",
            "c11": "Garment",
            "c12": "",
            "c13": "",
            "SKUAttribute14": "",
            "c15": "",
            "SkuLocAttribute1": "AREB5092",
            "SkuLocAttribute2": "38",
            "sl3": "AR",
            "sl4": "BZ",
            "sl5": "",
            "sl6": "",
            "sl7": "",
            "sl8": "",
            "sl9": "",
            "sl10": "AREB50924241",
            "sl11": "Yes",
            "sl12": "Jan-23",
            "sl13": "",
            "sl14": "",
            "sl15": "",
            "LocAttribute1": "EBO",
            "LocAttribute2": "10 to 12",
            "l3": "NCR",
            "l4": "D-2",
            "l5": "LTL",
            "l6": "NORTH",
            "l7": "Uttar Pradesh",
            "l8": "Ghaziabad",
            "l9": "EC",
            "l10": "",
            "l11": "",
            "l12": "",
            "l13": "",
            "l14": "",
            "l15": ""
        },
        {
            "RN": 13,
            "SKUCode": "AREB5092401",
            "SKUName": "SB2-NOTCH-KNIT-ZERO CALORIE-CORE",
            "LocCode": "4085",
            "LocName": "Rcity Ghatakopar|MUM",
            "OldNormValue": 1,
            "NewNormValue": 2,
            "Type": 10,
            "Comment": "Norm 1 Consumption based Increase",
            "PWhCode": "9020_EBO",
            "SKUAttribute1": "AREB5092",
            "SKUAttribute2": "40",
            "c3": "8.91E+12",
            "c4": "PC",
            "c5": "4999",
            "SKUAttribute6": "Arrow",
            "SKUAttribute7": "AR",
            "SKUAttribute8": "BZ",
            "SKUAttribute9": "CORE",
            "SKUAttribute10": "ZERO CALORIE",
            "c11": "Garment",
            "c12": "",
            "c13": "",
            "SKUAttribute14": "",
            "c15": "",
            "SkuLocAttribute1": "AREB5092",
            "SkuLocAttribute2": "40",
            "sl3": "AR",
            "sl4": "BZ",
            "sl5": "",
            "sl6": "",
            "sl7": "",
            "sl8": "",
            "sl9": "",
            "sl10": "AREB50924085",
            "sl11": "Yes",
            "sl12": "Nov-22",
            "sl13": "",
            "sl14": "",
            "sl15": "",
            "LocAttribute1": "EBO",
            "LocAttribute2": "10 to 15",
            "l3": "MUM",
            "l4": "D-36",
            "l5": "NLTL",
            "l6": "West",
            "l7": "Maharashtra",
            "l8": "Mumbai",
            "l9": "EC",
            "l10": "",
            "l11": "",
            "l12": "",
            "l13": "",
            "l14": "",
            "l15": ""
        },
        {
            "RN": 21,
            "SKUCode": "AREB5092421",
            "SKUName": "SB2-NOTCH-KNIT-ZERO CALORIE-CORE",
            "LocCode": "2031",
            "LocName": "Ambi|GUR",
            "OldNormValue": 2,
            "NewNormValue": 1,
            "Type": 11,
            "Comment": "Norm 2 Consumption based Decrease",
            "PWhCode": "9020_EBO",
            "SKUAttribute1": "AREB5092",
            "SKUAttribute2": "42",
            "c3": "8.91E+12",
            "c4": "PC",
            "c5": "4999",
            "SKUAttribute6": "Arrow",
            "SKUAttribute7": "AR",
            "SKUAttribute8": "BZ",
            "SKUAttribute9": "CORE",
            "SKUAttribute10": "ZERO CALORIE",
            "c11": "Garment",
            "c12": "",
            "c13": "",
            "SKUAttribute14": "",
            "c15": "",
            "SkuLocAttribute1": "AREB5092",
            "SkuLocAttribute2": "42",
            "sl3": "AR",
            "sl4": "BZ",
            "sl5": "",
            "sl6": "",
            "sl7": "",
            "sl8": "",
            "sl9": "",
            "sl10": "AREB50922031",
            "sl11": "Yes",
            "sl12": "Nov-22",
            "sl13": "",
            "sl14": "",
            "sl15": "",
            "LocAttribute1": "EBO",
            "LocAttribute2": "35 to 40",
            "l3": "NCR",
            "l4": "D-36",
            "l5": "LTL",
            "l6": "NORTH",
            "l7": "Haryana",
            "l8": "Gurugram",
            "l9": "EC",
            "l10": "",
            "l11": "",
            "l12": "",
            "l13": "",
            "l14": "",
            "l15": ""
        },
        {
            "RN": 29,
            "SKUCode": "AREB5092421",
            "SKUName": "SB2-NOTCH-KNIT-ZERO CALORIE-CORE",
            "LocCode": "4340",
            "LocName": "Forum|Cochin",
            "OldNormValue": 2,
            "NewNormValue": 1,
            "Type": 11,
            "Comment": "Norm 2 Consumption based Decrease",
            "PWhCode": "9020_EBO",
            "SKUAttribute1": "AREB5092",
            "SKUAttribute2": "42",
            "c3": "8.91E+12",
            "c4": "PC",
            "c5": "4999",
            "SKUAttribute6": "Arrow",
            "SKUAttribute7": "AR",
            "SKUAttribute8": "BZ",
            "SKUAttribute9": "CORE",
            "SKUAttribute10": "ZERO CALORIE",
            "c11": "Garment",
            "c12": "",
            "c13": "",
            "SKUAttribute14": "",
            "c15": "",
            "SkuLocAttribute1": "AREB5092",
            "SkuLocAttribute2": "42",
            "sl3": "AR",
            "sl4": "BZ",
            "sl5": "",
            "sl6": "",
            "sl7": "",
            "sl8": "",
            "sl9": "",
            "sl10": "",
            "sl11": "",
            "sl12": "06-09-2023",
            "sl13": "",
            "sl14": "",
            "sl15": "",
            "LocAttribute1": "EBO",
            "LocAttribute2": "10 to 15",
            "l3": "KL",
            "l4": "New-B",
            "l5": "",
            "l6": "South",
            "l7": "Kerala",
            "l8": "Ernakulam",
            "l9": "EC",
            "l10": "Yes",
            "l11": "",
            "l12": "",
            "l13": "",
            "l14": "",
            "l15": ""
        },
        {
            "RN": 8,
            "SKUCode": "AREB5092401",
            "SKUName": "SB2-NOTCH-KNIT-ZERO CALORIE-CORE",
            "LocCode": "2006",
            "LocName": "Khayala|DEL",
            "OldNormValue": 1,
            "NewNormValue": 2,
            "Type": 10,
            "Comment": "Norm 1 Consumption based Increase",
            "PWhCode": "9020_EBO",
            "SKUAttribute1": "AREB5092",
            "SKUAttribute2": "40",
            "c3": "8.91E+12",
            "c4": "PC",
            "c5": "4999",
            "SKUAttribute6": "Arrow",
            "SKUAttribute7": "AR",
            "SKUAttribute8": "BZ",
            "SKUAttribute9": "CORE",
            "SKUAttribute10": "ZERO CALORIE",
            "c11": "Garment",
            "c12": "",
            "c13": "",
            "SKUAttribute14": "",
            "c15": "",
            "SkuLocAttribute1": "AREB5092",
            "SkuLocAttribute2": "40",
            "sl3": "AR",
            "sl4": "BZ",
            "sl5": "",
            "sl6": "",
            "sl7": "",
            "sl8": "",
            "sl9": "",
            "sl10": "AREB50922006",
            "sl11": "Yes",
            "sl12": "Nov-22",
            "sl13": "",
            "sl14": "",
            "sl15": "",
            "LocAttribute1": "EBO",
            "LocAttribute2": "20 to 25",
            "l3": "NCR",
            "l4": "D-36",
            "l5": "LTL",
            "l6": "NORTH",
            "l7": "Delhi",
            "l8": "Delhi",
            "l9": "EC",
            "l10": "",
            "l11": "",
            "l12": "",
            "l13": "",
            "l14": "",
            "l15": ""
        },
        {
            "RN": 16,
            "SKUCode": "AREB5092401",
            "SKUName": "SB2-NOTCH-KNIT-ZERO CALORIE-CORE",
            "LocCode": "4337",
            "LocName": "Agartala",
            "OldNormValue": 1,
            "NewNormValue": 2,
            "Type": 10,
            "Comment": "Norm 1 Consumption based Increase",
            "PWhCode": "9020_EBO",
            "SKUAttribute1": "AREB5092",
            "SKUAttribute2": "40",
            "c3": "8.91E+12",
            "c4": "PC",
            "c5": "4999",
            "SKUAttribute6": "Arrow",
            "SKUAttribute7": "AR",
            "SKUAttribute8": "BZ",
            "SKUAttribute9": "CORE",
            "SKUAttribute10": "ZERO CALORIE",
            "c11": "Garment",
            "c12": "",
            "c13": "",
            "SKUAttribute14": "",
            "c15": "",
            "SkuLocAttribute1": "AREB5092",
            "SkuLocAttribute2": "40",
            "sl3": "AR",
            "sl4": "BZ",
            "sl5": "",
            "sl6": "",
            "sl7": "",
            "sl8": "",
            "sl9": "",
            "sl10": "",
            "sl11": "",
            "sl12": "06-09-2023",
            "sl13": "",
            "sl14": "",
            "sl15": "",
            "LocAttribute1": "EBO",
            "LocAttribute2": "15 to 20",
            "l3": "N.E.",
            "l4": "D-2",
            "l5": "LTL",
            "l6": "East",
            "l7": "Tripura",
            "l8": "Agartala",
            "l9": "EC",
            "l10": "Yes",
            "l11": "",
            "l12": "",
            "l13": "",
            "l14": "",
            "l15": ""
        },
        {
            "RN": 24,
            "SKUCode": "AREB5092421",
            "SKUName": "SB2-NOTCH-KNIT-ZERO CALORIE-CORE",
            "LocCode": "4052",
            "LocName": "MG|Cochin",
            "OldNormValue": 2,
            "NewNormValue": 1,
            "Type": 11,
            "Comment": "Norm 2 Consumption based Decrease",
            "PWhCode": "9020_EBO",
            "SKUAttribute1": "AREB5092",
            "SKUAttribute2": "42",
            "c3": "8.91E+12",
            "c4": "PC",
            "c5": "4999",
            "SKUAttribute6": "Arrow",
            "SKUAttribute7": "AR",
            "SKUAttribute8": "BZ",
            "SKUAttribute9": "CORE",
            "SKUAttribute10": "ZERO CALORIE",
            "c11": "Garment",
            "c12": "",
            "c13": "",
            "SKUAttribute14": "",
            "c15": "",
            "SkuLocAttribute1": "AREB5092",
            "SkuLocAttribute2": "42",
            "sl3": "AR",
            "sl4": "BZ",
            "sl5": "",
            "sl6": "",
            "sl7": "",
            "sl8": "",
            "sl9": "",
            "sl10": "AREB50924052",
            "sl11": "Yes",
            "sl12": "Nov-22",
            "sl13": "",
            "sl14": "",
            "sl15": "",
            "LocAttribute1": "EBO",
            "LocAttribute2": "10 to 15",
            "l3": "KL",
            "l4": "D-2",
            "l5": "NEW OPENED",
            "l6": "SOUTH",
            "l7": "Kerala",
            "l8": "Cochin",
            "l9": "EC",
            "l10": "",
            "l11": "",
            "l12": "",
            "l13": "",
            "l14": "",
            "l15": ""
        },
        {
            "RN": 32,
            "SKUCode": "AREB5093381",
            "SKUName": "SB2-NOTCH-KNIT-ZERO CALORIE-CORE",
            "LocCode": "4259",
            "LocName": "Grand Venice|Noida",
            "OldNormValue": 2,
            "NewNormValue": 1,
            "Type": 11,
            "Comment": "Norm 2 Consumption based Decrease",
            "PWhCode": "9020_EBO",
            "SKUAttribute1": "AREB5093",
            "SKUAttribute2": "38",
            "c3": "8.91E+12",
            "c4": "PC",
            "c5": "4999",
            "SKUAttribute6": "Arrow",
            "SKUAttribute7": "AR",
            "SKUAttribute8": "BZ",
            "SKUAttribute9": "CORE",
            "SKUAttribute10": "ZERO CALORIE",
            "c11": "Garment",
            "c12": "",
            "c13": "",
            "SKUAttribute14": "",
            "c15": "",
            "SkuLocAttribute1": "AREB5093",
            "SkuLocAttribute2": "38",
            "sl3": "AR",
            "sl4": "BZ",
            "sl5": "",
            "sl6": "",
            "sl7": "",
            "sl8": "",
            "sl9": "",
            "sl10": "AREB50934259",
            "sl11": "Yes",
            "sl12": "Mar-23",
            "sl13": "",
            "sl14": "",
            "sl15": "",
            "LocAttribute1": "EBO",
            "LocAttribute2": "20 to 25",
            "l3": "NCR",
            "l4": "NOT",
            "l5": "New",
            "l6": "North",
            "l7": "Uttar Pradesh",
            "l8": "Noida",
            "l9": "EC",
            "l10": "Yes",
            "l11": "",
            "l12": "",
            "l13": "",
            "l14": "",
            "l15": ""
        },
        {
            "RN": 6,
            "SKUCode": "AREB5092381",
            "SKUName": "SB2-NOTCH-KNIT-ZERO CALORIE-CORE",
            "LocCode": "4320",
            "LocName": "Palassio|LKO",
            "OldNormValue": 1,
            "NewNormValue": 2,
            "Type": 10,
            "Comment": "Norm 1 Consumption based Increase",
            "PWhCode": "9020_EBO",
            "SKUAttribute1": "AREB5092",
            "SKUAttribute2": "38",
            "c3": "8.91E+12",
            "c4": "PC",
            "c5": "4999",
            "SKUAttribute6": "Arrow",
            "SKUAttribute7": "AR",
            "SKUAttribute8": "BZ",
            "SKUAttribute9": "CORE",
            "SKUAttribute10": "ZERO CALORIE",
            "c11": "Garment",
            "c12": "",
            "c13": "",
            "SKUAttribute14": "",
            "c15": "",
            "SkuLocAttribute1": "AREB5092",
            "SkuLocAttribute2": "38",
            "sl3": "AR",
            "sl4": "BZ",
            "sl5": "",
            "sl6": "",
            "sl7": "",
            "sl8": "",
            "sl9": "",
            "sl10": "AREB50924320",
            "sl11": "Yes",
            "sl12": "Jul-23",
            "sl13": "",
            "sl14": "",
            "sl15": "",
            "LocAttribute1": "EBO",
            "LocAttribute2": "20 to 25",
            "l3": "UP/UK",
            "l4": "D-36",
            "l5": "New",
            "l6": "North",
            "l7": "Uttar Pradesh",
            "l8": "Lucknow",
            "l9": "EC",
            "l10": "Yes",
            "l11": "",
            "l12": "",
            "l13": "",
            "l14": "",
            "l15": ""
        },
        {
            "RN": 14,
            "SKUCode": "AREB5092401",
            "SKUName": "SB2-NOTCH-KNIT-ZERO CALORIE-CORE",
            "LocCode": "4165",
            "LocName": "Lulu|LKO",
            "OldNormValue": 1,
            "NewNormValue": 2,
            "Type": 10,
            "Comment": "Norm 1 Consumption based Increase",
            "PWhCode": "9020_EBO",
            "SKUAttribute1": "AREB5092",
            "SKUAttribute2": "40",
            "c3": "8.91E+12",
            "c4": "PC",
            "c5": "4999",
            "SKUAttribute6": "Arrow",
            "SKUAttribute7": "AR",
            "SKUAttribute8": "BZ",
            "SKUAttribute9": "CORE",
            "SKUAttribute10": "ZERO CALORIE",
            "c11": "Garment",
            "c12": "",
            "c13": "",
            "SKUAttribute14": "",
            "c15": "",
            "SkuLocAttribute1": "AREB5092",
            "SkuLocAttribute2": "40",
            "sl3": "AR",
            "sl4": "BZ",
            "sl5": "",
            "sl6": "",
            "sl7": "",
            "sl8": "",
            "sl9": "",
            "sl10": "AREB50924165",
            "sl11": "Yes",
            "sl12": "Nov-22",
            "sl13": "",
            "sl14": "",
            "sl15": "",
            "LocAttribute1": "EBO",
            "LocAttribute2": "15 to 20",
            "l3": "UP/UK",
            "l4": "D-1",
            "l5": "NEW OPENED",
            "l6": "NORTH",
            "l7": "Uttar Pradesh",
            "l8": "Lucknow",
            "l9": "EC",
            "l10": "",
            "l11": "",
            "l12": "",
            "l13": "",
            "l14": "",
            "l15": ""
        },
        {
            "RN": 22,
            "SKUCode": "AREB5092421",
            "SKUName": "SB2-NOTCH-KNIT-ZERO CALORIE-CORE",
            "LocCode": "2208",
            "LocName": "Oberoi|MUM",
            "OldNormValue": 2,
            "NewNormValue": 1,
            "Type": 11,
            "Comment": "Norm 2 Consumption based Decrease",
            "PWhCode": "9020_EBO",
            "SKUAttribute1": "AREB5092",
            "SKUAttribute2": "42",
            "c3": "8.91E+12",
            "c4": "PC",
            "c5": "4999",
            "SKUAttribute6": "Arrow",
            "SKUAttribute7": "AR",
            "SKUAttribute8": "BZ",
            "SKUAttribute9": "CORE",
            "SKUAttribute10": "ZERO CALORIE",
            "c11": "Garment",
            "c12": "",
            "c13": "",
            "SKUAttribute14": "",
            "c15": "",
            "SkuLocAttribute1": "AREB5092",
            "SkuLocAttribute2": "42",
            "sl3": "AR",
            "sl4": "BZ",
            "sl5": "",
            "sl6": "",
            "sl7": "",
            "sl8": "",
            "sl9": "",
            "sl10": "AREB50922208",
            "sl11": "Yes",
            "sl12": "Nov-22",
            "sl13": "",
            "sl14": "",
            "sl15": "",
            "LocAttribute1": "EBO",
            "LocAttribute2": "10 to 15",
            "l3": "MUM",
            "l4": "D-36",
            "l5": "LTL",
            "l6": "WEST",
            "l7": "Maharashtra",
            "l8": "Mumbai",
            "l9": "EC",
            "l10": "",
            "l11": "",
            "l12": "",
            "l13": "",
            "l14": "",
            "l15": ""
        },
        {
            "RN": 30,
            "SKUCode": "AREB5092441",
            "SKUName": "SB2-NOTCH-KNIT-ZERO CALORIE-CORE",
            "LocCode": "2239",
            "LocName": "Annannagar|CHN",
            "OldNormValue": 1,
            "NewNormValue": 2,
            "Type": 10,
            "Comment": "Norm 1 Consumption based Increase",
            "PWhCode": "9020_EBO",
            "SKUAttribute1": "AREB5092",
            "SKUAttribute2": "44",
            "c3": "8.91E+12",
            "c4": "PC",
            "c5": "4999",
            "SKUAttribute6": "Arrow",
            "SKUAttribute7": "AR",
            "SKUAttribute8": "BZ",
            "SKUAttribute9": "CORE",
            "SKUAttribute10": "ZERO CALORIE",
            "c11": "Garment",
            "c12": "",
            "c13": "",
            "SKUAttribute14": "",
            "c15": "",
            "SkuLocAttribute1": "AREB5092",
            "SkuLocAttribute2": "44",
            "sl3": "AR",
            "sl4": "BZ",
            "sl5": "",
            "sl6": "",
            "sl7": "",
            "sl8": "",
            "sl9": "",
            "sl10": "AREB50922239",
            "sl11": "Yes",
            "sl12": "Nov-22",
            "sl13": "",
            "sl14": "",
            "sl15": "",
            "LocAttribute1": "EBO",
            "LocAttribute2": "10 to 15",
            "l3": "TN",
            "l4": "D-1",
            "l5": "NLTL",
            "l6": "SOUTH",
            "l7": "Tamil Nadu",
            "l8": "Chennai",
            "l9": "EC",
            "l10": "",
            "l11": "",
            "l12": "",
            "l13": "",
            "l14": "",
            "l15": ""
        },
        {
            "RN": 34,
            "SKUCode": "AREB5093381",
            "SKUName": "SB2-NOTCH-KNIT-ZERO CALORIE-CORE",
            "LocCode": "4342",
            "LocName": "Shillong|Meghalaya",
            "OldNormValue": 2,
            "NewNormValue": 1,
            "Type": 11,
            "Comment": "Norm 2 Consumption based Decrease",
            "PWhCode": "9020_EBO",
            "SKUAttribute1": "AREB5093",
            "SKUAttribute2": "38",
            "c3": "8.91E+12",
            "c4": "PC",
            "c5": "4999",
            "SKUAttribute6": "Arrow",
            "SKUAttribute7": "AR",
            "SKUAttribute8": "BZ",
            "SKUAttribute9": "CORE",
            "SKUAttribute10": "ZERO CALORIE",
            "c11": "Garment",
            "c12": "",
            "c13": "",
            "SKUAttribute14": "",
            "c15": "",
            "SkuLocAttribute1": "AREB5093",
            "SkuLocAttribute2": "38",
            "sl3": "AR",
            "sl4": "BZ",
            "sl5": "",
            "sl6": "",
            "sl7": "",
            "sl8": "",
            "sl9": "",
            "sl10": "",
            "sl11": "",
            "sl12": "06-09-2023",
            "sl13": "",
            "sl14": "",
            "sl15": "",
            "LocAttribute1": "EBO",
            "LocAttribute2": "10 to 15",
            "l3": "N.E.",
            "l4": "New-B",
            "l5": "",
            "l6": "East",
            "l7": "Meghalaya",
            "l8": "Meghalaya",
            "l9": "EC",
            "l10": "Yes",
            "l11": "",
            "l12": "",
            "l13": "",
            "l14": "",
            "l15": ""
        },
        {
            "RN": 42,
            "SKUCode": "AREB5093421",
            "SKUName": "SB2-NOTCH-KNIT-ZERO CALORIE-CORE",
            "LocCode": "4082",
            "LocName": "Forum|HYD",
            "OldNormValue": 2,
            "NewNormValue": 1,
            "Type": 11,
            "Comment": "Norm 2 Consumption based Decrease",
            "PWhCode": "9020_EBO",
            "SKUAttribute1": "AREB5093",
            "SKUAttribute2": "42",
            "c3": "8.91E+12",
            "c4": "PC",
            "c5": "4999",
            "SKUAttribute6": "Arrow",
            "SKUAttribute7": "AR",
            "SKUAttribute8": "BZ",
            "SKUAttribute9": "CORE",
            "SKUAttribute10": "ZERO CALORIE",
            "c11": "Garment",
            "c12": "",
            "c13": "",
            "SKUAttribute14": "",
            "c15": "",
            "SkuLocAttribute1": "AREB5093",
            "SkuLocAttribute2": "42",
            "sl3": "AR",
            "sl4": "BZ",
            "sl5": "",
            "sl6": "",
            "sl7": "",
            "sl8": "",
            "sl9": "",
            "sl10": "AREB50934082",
            "sl11": "Yes",
            "sl12": "Nov-22",
            "sl13": "",
            "sl14": "",
            "sl15": "",
            "LocAttribute1": "EBO",
            "LocAttribute2": "10 to 15",
            "l3": "AP/TS",
            "l4": "D-36",
            "l5": "LTL",
            "l6": "SOUTH",
            "l7": "Ap/Tl",
            "l8": "Hyderabad",
            "l9": "EC",
            "l10": "",
            "l11": "",
            "l12": "",
            "l13": "",
            "l14": "",
            "l15": ""
        },
        {
            "RN": 50,
            "SKUCode": "AREB5093441",
            "SKUName": "SB2-NOTCH-KNIT-ZERO CALORIE-CORE",
            "LocCode": "4061",
            "LocName": "New Bel Rd.|BLR",
            "OldNormValue": 2,
            "NewNormValue": 1,
            "Type": 11,
            "Comment": "Norm 2 Consumption based Decrease",
            "PWhCode": "9020_EBO",
            "SKUAttribute1": "AREB5093",
            "SKUAttribute2": "44",
            "c3": "8.91E+12",
            "c4": "PC",
            "c5": "4999",
            "SKUAttribute6": "Arrow",
            "SKUAttribute7": "AR",
            "SKUAttribute8": "BZ",
            "SKUAttribute9": "CORE",
            "SKUAttribute10": "ZERO CALORIE",
            "c11": "Garment",
            "c12": "",
            "c13": "",
            "SKUAttribute14": "",
            "c15": "",
            "SkuLocAttribute1": "AREB5093",
            "SkuLocAttribute2": "44",
            "sl3": "AR",
            "sl4": "BZ",
            "sl5": "",
            "sl6": "",
            "sl7": "",
            "sl8": "",
            "sl9": "",
            "sl10": "AREB50934061",
            "sl11": "Yes",
            "sl12": "Jan-23",
            "sl13": "",
            "sl14": "",
            "sl15": "",
            "LocAttribute1": "EBO",
            "LocAttribute2": "15 to 20",
            "l3": "KAR",
            "l4": "D-1",
            "l5": "LTL",
            "l6": "SOUTH",
            "l7": "Karnataka",
            "l8": "Bengaluru",
            "l9": "EC",
            "l10": "",
            "l11": "",
            "l12": "",
            "l13": "",
            "l14": "",
            "l15": ""
        },
        {
            "RN": 35,
            "SKUCode": "AREB5093401",
            "SKUName": "SB2-NOTCH-KNIT-ZERO CALORIE-CORE",
            "LocCode": "2114",
            "LocName": "Store1|Imphal",
            "OldNormValue": 2,
            "NewNormValue": 1,
            "Type": 11,
            "Comment": "Norm 2 Consumption based Decrease",
            "PWhCode": "9020_EBO",
            "SKUAttribute1": "AREB5093",
            "SKUAttribute2": "40",
            "c3": "8.91E+12",
            "c4": "PC",
            "c5": "4999",
            "SKUAttribute6": "Arrow",
            "SKUAttribute7": "AR",
            "SKUAttribute8": "BZ",
            "SKUAttribute9": "CORE",
            "SKUAttribute10": "ZERO CALORIE",
            "c11": "Garment",
            "c12": "",
            "c13": "",
            "SKUAttribute14": "",
            "c15": "",
            "SkuLocAttribute1": "AREB5093",
            "SkuLocAttribute2": "40",
            "sl3": "AR",
            "sl4": "BZ",
            "sl5": "",
            "sl6": "",
            "sl7": "",
            "sl8": "",
            "sl9": "",
            "sl10": "AREB50932114",
            "sl11": "Yes",
            "sl12": "Nov-22",
            "sl13": "",
            "sl14": "",
            "sl15": "",
            "LocAttribute1": "EBO",
            "LocAttribute2": "20 to 25",
            "l3": "N.E.",
            "l4": "D-36",
            "l5": "LTL",
            "l6": "EAST",
            "l7": "Manipur",
            "l8": "Imphal",
            "l9": "EC",
            "l10": "",
            "l11": "",
            "l12": "",
            "l13": "",
            "l14": "",
            "l15": ""
        },
        {
            "RN": 43,
            "SKUCode": "AREB5093421",
            "SKUName": "SB2-NOTCH-KNIT-ZERO CALORIE-CORE",
            "LocCode": "4084",
            "LocName": "Lulu|BLR",
            "OldNormValue": 2,
            "NewNormValue": 1,
            "Type": 11,
            "Comment": "Norm 2 Consumption based Decrease",
            "PWhCode": "9020_EBO",
            "SKUAttribute1": "AREB5093",
            "SKUAttribute2": "42",
            "c3": "8.91E+12",
            "c4": "PC",
            "c5": "4999",
            "SKUAttribute6": "Arrow",
            "SKUAttribute7": "AR",
            "SKUAttribute8": "BZ",
            "SKUAttribute9": "CORE",
            "SKUAttribute10": "ZERO CALORIE",
            "c11": "Garment",
            "c12": "",
            "c13": "",
            "SKUAttribute14": "",
            "c15": "",
            "SkuLocAttribute1": "AREB5093",
            "SkuLocAttribute2": "42",
            "sl3": "AR",
            "sl4": "BZ",
            "sl5": "",
            "sl6": "",
            "sl7": "",
            "sl8": "",
            "sl9": "",
            "sl10": "AREB50934084",
            "sl11": "Yes",
            "sl12": "Nov-22",
            "sl13": "",
            "sl14": "",
            "sl15": "",
            "LocAttribute1": "EBO",
            "LocAttribute2": "25 to 30",
            "l3": "KAR",
            "l4": "D-1",
            "l5": "NEW OPENED",
            "l6": "SOUTH",
            "l7": "Karnataka",
            "l8": "Bengaluru",
            "l9": "EC",
            "l10": "",
            "l11": "",
            "l12": "",
            "l13": "",
            "l14": "",
            "l15": ""
        },
        {
            "RN": 37,
            "SKUCode": "AREB5093401",
            "SKUName": "SB2-NOTCH-KNIT-ZERO CALORIE-CORE",
            "LocCode": "4179",
            "LocName": "Gorakhpur",
            "OldNormValue": 2,
            "NewNormValue": 1,
            "Type": 11,
            "Comment": "Norm 2 Consumption based Decrease",
            "PWhCode": "9020_EBO",
            "SKUAttribute1": "AREB5093",
            "SKUAttribute2": "40",
            "c3": "8.91E+12",
            "c4": "PC",
            "c5": "4999",
            "SKUAttribute6": "Arrow",
            "SKUAttribute7": "AR",
            "SKUAttribute8": "BZ",
            "SKUAttribute9": "CORE",
            "SKUAttribute10": "ZERO CALORIE",
            "c11": "Garment",
            "c12": "",
            "c13": "",
            "SKUAttribute14": "",
            "c15": "",
            "SkuLocAttribute1": "AREB5093",
            "SkuLocAttribute2": "40",
            "sl3": "AR",
            "sl4": "BZ",
            "sl5": "",
            "sl6": "",
            "sl7": "",
            "sl8": "",
            "sl9": "",
            "sl10": "AREB50934179",
            "sl11": "Yes",
            "sl12": "Jan-23",
            "sl13": "",
            "sl14": "",
            "sl15": "",
            "LocAttribute1": "EBO",
            "LocAttribute2": "10 to 15",
            "l3": "UP/UK",
            "l4": "D-1",
            "l5": "NEW OPENED",
            "l6": "NORTH",
            "l7": "Uttar Pradesh",
            "l8": "Gorakpur",
            "l9": "EC",
            "l10": "",
            "l11": "",
            "l12": "",
            "l13": "",
            "l14": "",
            "l15": ""
        },
        {
            "RN": 45,
            "SKUCode": "AREB5093421",
            "SKUName": "SB2-NOTCH-KNIT-ZERO CALORIE-CORE",
            "LocCode": "4237",
            "LocName": "Falcon Kanakpura|BLR",
            "OldNormValue": 2,
            "NewNormValue": 1,
            "Type": 11,
            "Comment": "Norm 2 Consumption based Decrease",
            "PWhCode": "9020_EBO",
            "SKUAttribute1": "AREB5093",
            "SKUAttribute2": "42",
            "c3": "8.91E+12",
            "c4": "PC",
            "c5": "4999",
            "SKUAttribute6": "Arrow",
            "SKUAttribute7": "AR",
            "SKUAttribute8": "BZ",
            "SKUAttribute9": "CORE",
            "SKUAttribute10": "ZERO CALORIE",
            "c11": "Garment",
            "c12": "",
            "c13": "",
            "SKUAttribute14": "",
            "c15": "",
            "SkuLocAttribute1": "AREB5093",
            "SkuLocAttribute2": "42",
            "sl3": "AR",
            "sl4": "BZ",
            "sl5": "",
            "sl6": "",
            "sl7": "",
            "sl8": "",
            "sl9": "",
            "sl10": "AREB50934237",
            "sl11": "Yes",
            "sl12": "Nov-22",
            "sl13": "",
            "sl14": "",
            "sl15": "",
            "LocAttribute1": "EBO",
            "LocAttribute2": "15 to 20",
            "l3": "KAR",
            "l4": "D-1",
            "l5": "NEW OPENED",
            "l6": "SOUTH",
            "l7": "Karnataka",
            "l8": "BENGALURU",
            "l9": "EC",
            "l10": "",
            "l11": "",
            "l12": "",
            "l13": "",
            "l14": "",
            "l15": ""
        },
        {
            "RN": 40,
            "SKUCode": "AREB5093401",
            "SKUName": "SB2-NOTCH-KNIT-ZERO CALORIE-CORE",
            "LocCode": "4343",
            "LocName": "Inter|Ranchi",
            "OldNormValue": 2,
            "NewNormValue": 1,
            "Type": 11,
            "Comment": "Norm 2 Consumption based Decrease",
            "PWhCode": "9020_EBO",
            "SKUAttribute1": "AREB5093",
            "SKUAttribute2": "40",
            "c3": "8.91E+12",
            "c4": "PC",
            "c5": "4999",
            "SKUAttribute6": "Arrow",
            "SKUAttribute7": "AR",
            "SKUAttribute8": "BZ",
            "SKUAttribute9": "CORE",
            "SKUAttribute10": "ZERO CALORIE",
            "c11": "Garment",
            "c12": "",
            "c13": "",
            "SKUAttribute14": "",
            "c15": "",
            "SkuLocAttribute1": "AREB5093",
            "SkuLocAttribute2": "40",
            "sl3": "AR",
            "sl4": "BZ",
            "sl5": "",
            "sl6": "",
            "sl7": "",
            "sl8": "",
            "sl9": "",
            "sl10": "",
            "sl11": "",
            "sl12": "06-09-2023",
            "sl13": "",
            "sl14": "",
            "sl15": "",
            "LocAttribute1": "EBO",
            "LocAttribute2": "10 to 15",
            "l3": "BR/JH",
            "l4": "D-2",
            "l5": "",
            "l6": "East",
            "l7": "Jharkhand",
            "l8": "Ranchi",
            "l9": "EC",
            "l10": "Yes",
            "l11": "",
            "l12": "",
            "l13": "",
            "l14": "",
            "l15": ""
        },
        {
            "RN": 48,
            "SKUCode": "AREB5093421",
            "SKUName": "SB2-NOTCH-KNIT-ZERO CALORIE-CORE",
            "LocCode": "4344",
            "LocName": "Gandhinagar",
            "OldNormValue": 2,
            "NewNormValue": 1,
            "Type": 11,
            "Comment": "Norm 2 Consumption based Decrease",
            "PWhCode": "9020_EBO",
            "SKUAttribute1": "AREB5093",
            "SKUAttribute2": "42",
            "c3": "8.91E+12",
            "c4": "PC",
            "c5": "4999",
            "SKUAttribute6": "Arrow",
            "SKUAttribute7": "AR",
            "SKUAttribute8": "BZ",
            "SKUAttribute9": "CORE",
            "SKUAttribute10": "ZERO CALORIE",
            "c11": "Garment",
            "c12": "",
            "c13": "",
            "SKUAttribute14": "",
            "c15": "",
            "SkuLocAttribute1": "AREB5093",
            "SkuLocAttribute2": "42",
            "sl3": "AR",
            "sl4": "BZ",
            "sl5": "",
            "sl6": "",
            "sl7": "",
            "sl8": "",
            "sl9": "",
            "sl10": "",
            "sl11": "",
            "sl12": "06-09-2023",
            "sl13": "",
            "sl14": "",
            "sl15": "",
            "LocAttribute1": "EBO",
            "LocAttribute2": "10 to 15",
            "l3": "GUJ",
            "l4": "New-B",
            "l5": "",
            "l6": "West",
            "l7": "Gujarat",
            "l8": "Gandhinagar",
            "l9": "EC",
            "l10": "Yes",
            "l11": "",
            "l12": "",
            "l13": "",
            "l14": "",
            "l15": ""
        },
        {
            "RN": 39,
            "SKUCode": "AREB5093401",
            "SKUName": "SB2-NOTCH-KNIT-ZERO CALORIE-CORE",
            "LocCode": "4341",
            "LocName": "Mall Of Ranchi|Ranchi",
            "OldNormValue": 2,
            "NewNormValue": 1,
            "Type": 11,
            "Comment": "Norm 2 Consumption based Decrease",
            "PWhCode": "9020_EBO",
            "SKUAttribute1": "AREB5093",
            "SKUAttribute2": "40",
            "c3": "8.91E+12",
            "c4": "PC",
            "c5": "4999",
            "SKUAttribute6": "Arrow",
            "SKUAttribute7": "AR",
            "SKUAttribute8": "BZ",
            "SKUAttribute9": "CORE",
            "SKUAttribute10": "ZERO CALORIE",
            "c11": "Garment",
            "c12": "",
            "c13": "",
            "SKUAttribute14": "",
            "c15": "",
            "SkuLocAttribute1": "AREB5093",
            "SkuLocAttribute2": "40",
            "sl3": "AR",
            "sl4": "BZ",
            "sl5": "",
            "sl6": "",
            "sl7": "",
            "sl8": "",
            "sl9": "",
            "sl10": "",
            "sl11": "",
            "sl12": "06-09-2023",
            "sl13": "",
            "sl14": "",
            "sl15": "",
            "LocAttribute1": "EBO",
            "LocAttribute2": "10 to 15",
            "l3": "BR/JH",
            "l4": "NOT",
            "l5": "",
            "l6": "East",
            "l7": "Jharkhand",
            "l8": "Ranchi",
            "l9": "EC",
            "l10": "Yes",
            "l11": "",
            "l12": "",
            "l13": "",
            "l14": "",
            "l15": ""
        },
        {
            "RN": 47,
            "SKUCode": "AREB5093421",
            "SKUName": "SB2-NOTCH-KNIT-ZERO CALORIE-CORE",
            "LocCode": "4240",
            "LocName": "Mansarovar|JPR",
            "OldNormValue": 2,
            "NewNormValue": 1,
            "Type": 11,
            "Comment": "Norm 2 Consumption based Decrease",
            "PWhCode": "9020_EBO",
            "SKUAttribute1": "AREB5093",
            "SKUAttribute2": "42",
            "c3": "8.91E+12",
            "c4": "PC",
            "c5": "4999",
            "SKUAttribute6": "Arrow",
            "SKUAttribute7": "AR",
            "SKUAttribute8": "BZ",
            "SKUAttribute9": "CORE",
            "SKUAttribute10": "ZERO CALORIE",
            "c11": "Garment",
            "c12": "",
            "c13": "",
            "SKUAttribute14": "",
            "c15": "",
            "SkuLocAttribute1": "AREB5093",
            "SkuLocAttribute2": "42",
            "sl3": "AR",
            "sl4": "BZ",
            "sl5": "",
            "sl6": "",
            "sl7": "",
            "sl8": "",
            "sl9": "",
            "sl10": "AREB50934240",
            "sl11": "Yes",
            "sl12": "Dec-22",
            "sl13": "",
            "sl14": "",
            "sl15": "",
            "LocAttribute1": "EBO",
            "LocAttribute2": "10 to 15",
            "l3": "RAJ",
            "l4": "D-2",
            "l5": "New",
            "l6": "North",
            "l7": "Rajasthan",
            "l8": "Jaipur",
            "l9": "EC",
            "l10": "Yes",
            "l11": "",
            "l12": "",
            "l13": "",
            "l14": "",
            "l15": ""
        },
        {
            "RN": 33,
            "SKUCode": "AREB5093381",
            "SKUName": "SB2-NOTCH-KNIT-ZERO CALORIE-CORE",
            "LocCode": "4341",
            "LocName": "Mall Of Ranchi|Ranchi",
            "OldNormValue": 2,
            "NewNormValue": 1,
            "Type": 11,
            "Comment": "Norm 2 Consumption based Decrease",
            "PWhCode": "9020_EBO",
            "SKUAttribute1": "AREB5093",
            "SKUAttribute2": "38",
            "c3": "8.91E+12",
            "c4": "PC",
            "c5": "4999",
            "SKUAttribute6": "Arrow",
            "SKUAttribute7": "AR",
            "SKUAttribute8": "BZ",
            "SKUAttribute9": "CORE",
            "SKUAttribute10": "ZERO CALORIE",
            "c11": "Garment",
            "c12": "",
            "c13": "",
            "SKUAttribute14": "",
            "c15": "",
            "SkuLocAttribute1": "AREB5093",
            "SkuLocAttribute2": "38",
            "sl3": "AR",
            "sl4": "BZ",
            "sl5": "",
            "sl6": "",
            "sl7": "",
            "sl8": "",
            "sl9": "",
            "sl10": "",
            "sl11": "",
            "sl12": "06-09-2023",
            "sl13": "",
            "sl14": "",
            "sl15": "",
            "LocAttribute1": "EBO",
            "LocAttribute2": "10 to 15",
            "l3": "BR/JH",
            "l4": "NOT",
            "l5": "",
            "l6": "East",
            "l7": "Jharkhand",
            "l8": "Ranchi",
            "l9": "EC",
            "l10": "Yes",
            "l11": "",
            "l12": "",
            "l13": "",
            "l14": "",
            "l15": ""
        },
        {
            "RN": 41,
            "SKUCode": "AREB5093421",
            "SKUName": "SB2-NOTCH-KNIT-ZERO CALORIE-CORE",
            "LocCode": "4052",
            "LocName": "MG|Cochin",
            "OldNormValue": 2,
            "NewNormValue": 1,
            "Type": 11,
            "Comment": "Norm 2 Consumption based Decrease",
            "PWhCode": "9020_EBO",
            "SKUAttribute1": "AREB5093",
            "SKUAttribute2": "42",
            "c3": "8.91E+12",
            "c4": "PC",
            "c5": "4999",
            "SKUAttribute6": "Arrow",
            "SKUAttribute7": "AR",
            "SKUAttribute8": "BZ",
            "SKUAttribute9": "CORE",
            "SKUAttribute10": "ZERO CALORIE",
            "c11": "Garment",
            "c12": "",
            "c13": "",
            "SKUAttribute14": "",
            "c15": "",
            "SkuLocAttribute1": "AREB5093",
            "SkuLocAttribute2": "42",
            "sl3": "AR",
            "sl4": "BZ",
            "sl5": "",
            "sl6": "",
            "sl7": "",
            "sl8": "",
            "sl9": "",
            "sl10": "AREB50934052",
            "sl11": "Yes",
            "sl12": "Nov-22",
            "sl13": "",
            "sl14": "",
            "sl15": "",
            "LocAttribute1": "EBO",
            "LocAttribute2": "10 to 15",
            "l3": "KL",
            "l4": "D-2",
            "l5": "NEW OPENED",
            "l6": "SOUTH",
            "l7": "Kerala",
            "l8": "Cochin",
            "l9": "EC",
            "l10": "",
            "l11": "",
            "l12": "",
            "l13": "",
            "l14": "",
            "l15": ""
        },
        {
            "RN": 49,
            "SKUCode": "AREB5093441",
            "SKUName": "SB2-NOTCH-KNIT-ZERO CALORIE-CORE",
            "LocCode": "2073",
            "LocName": "Wave|Jammu",
            "OldNormValue": 2,
            "NewNormValue": 1,
            "Type": 11,
            "Comment": "Norm 2 Consumption based Decrease",
            "PWhCode": "9020_EBO",
            "SKUAttribute1": "AREB5093",
            "SKUAttribute2": "44",
            "c3": "8.91E+12",
            "c4": "PC",
            "c5": "4999",
            "SKUAttribute6": "Arrow",
            "SKUAttribute7": "AR",
            "SKUAttribute8": "BZ",
            "SKUAttribute9": "CORE",
            "SKUAttribute10": "ZERO CALORIE",
            "c11": "Garment",
            "c12": "",
            "c13": "",
            "SKUAttribute14": "",
            "c15": "",
            "SkuLocAttribute1": "AREB5093",
            "SkuLocAttribute2": "44",
            "sl3": "AR",
            "sl4": "BZ",
            "sl5": "",
            "sl6": "",
            "sl7": "",
            "sl8": "",
            "sl9": "",
            "sl10": "AREB50932073",
            "sl11": "Yes",
            "sl12": "Jan-23",
            "sl13": "",
            "sl14": "",
            "sl15": "",
            "LocAttribute1": "EBO",
            "LocAttribute2": "15 to 20",
            "l3": "Punjab",
            "l4": "D-36",
            "l5": "LTL",
            "l6": "NORTH",
            "l7": "Jammu And Kashmir",
            "l8": "Jammu",
            "l9": "EC",
            "l10": "",
            "l11": "",
            "l12": "",
            "l13": "",
            "l14": "",
            "l15": ""
        },
        {
            "RN": 36,
            "SKUCode": "AREB5093401",
            "SKUName": "SB2-NOTCH-KNIT-ZERO CALORIE-CORE",
            "LocCode": "4159",
            "LocName": "Basweshwar|BLR",
            "OldNormValue": 2,
            "NewNormValue": 1,
            "Type": 11,
            "Comment": "Norm 2 Consumption based Decrease",
            "PWhCode": "9020_EBO",
            "SKUAttribute1": "AREB5093",
            "SKUAttribute2": "40",
            "c3": "8.91E+12",
            "c4": "PC",
            "c5": "4999",
            "SKUAttribute6": "Arrow",
            "SKUAttribute7": "AR",
            "SKUAttribute8": "BZ",
            "SKUAttribute9": "CORE",
            "SKUAttribute10": "ZERO CALORIE",
            "c11": "Garment",
            "c12": "",
            "c13": "",
            "SKUAttribute14": "",
            "c15": "",
            "SkuLocAttribute1": "AREB5093",
            "SkuLocAttribute2": "40",
            "sl3": "AR",
            "sl4": "BZ",
            "sl5": "",
            "sl6": "",
            "sl7": "",
            "sl8": "",
            "sl9": "",
            "sl10": "AREB50934159",
            "sl11": "Yes",
            "sl12": "Nov-22",
            "sl13": "",
            "sl14": "",
            "sl15": "",
            "LocAttribute1": "EBO",
            "LocAttribute2": "5 to 10",
            "l3": "KAR",
            "l4": "D-2",
            "l5": "NEW OPENED",
            "l6": "SOUTH",
            "l7": "Karnataka",
            "l8": "Benguluru",
            "l9": "EC",
            "l10": "",
            "l11": "",
            "l12": "",
            "l13": "",
            "l14": "",
            "l15": ""
        },
        {
            "RN": 44,
            "SKUCode": "AREB5093421",
            "SKUName": "SB2-NOTCH-KNIT-ZERO CALORIE-CORE",
            "LocCode": "4182",
            "LocName": "Commercial St|BLR",
            "OldNormValue": 2,
            "NewNormValue": 1,
            "Type": 11,
            "Comment": "Norm 2 Consumption based Decrease",
            "PWhCode": "9020_EBO",
            "SKUAttribute1": "AREB5093",
            "SKUAttribute2": "42",
            "c3": "8.91E+12",
            "c4": "PC",
            "c5": "4999",
            "SKUAttribute6": "Arrow",
            "SKUAttribute7": "AR",
            "SKUAttribute8": "BZ",
            "SKUAttribute9": "CORE",
            "SKUAttribute10": "ZERO CALORIE",
            "c11": "Garment",
            "c12": "",
            "c13": "",
            "SKUAttribute14": "",
            "c15": "",
            "SkuLocAttribute1": "AREB5093",
            "SkuLocAttribute2": "42",
            "sl3": "AR",
            "sl4": "BZ",
            "sl5": "",
            "sl6": "",
            "sl7": "",
            "sl8": "",
            "sl9": "",
            "sl10": "AREB50934182",
            "sl11": "Yes",
            "sl12": "Jan-23",
            "sl13": "",
            "sl14": "",
            "sl15": "",
            "LocAttribute1": "EBO",
            "LocAttribute2": "25 to 30",
            "l3": "KAR",
            "l4": "D-36",
            "l5": "NEW OPENED",
            "l6": "SOUTH",
            "l7": "Karnataka",
            "l8": "Benguluru",
            "l9": "EC",
            "l10": "",
            "l11": "",
            "l12": "",
            "l13": "",
            "l14": "",
            "l15": ""
        },
        {
            "RN": 38,
            "SKUCode": "AREB5093401",
            "SKUName": "SB2-NOTCH-KNIT-ZERO CALORIE-CORE",
            "LocCode": "4189",
            "LocName": "Agra",
            "OldNormValue": 2,
            "NewNormValue": 1,
            "Type": 11,
            "Comment": "Norm 2 Consumption based Decrease",
            "PWhCode": "9020_EBO",
            "SKUAttribute1": "AREB5093",
            "SKUAttribute2": "40",
            "c3": "8.91E+12",
            "c4": "PC",
            "c5": "4999",
            "SKUAttribute6": "Arrow",
            "SKUAttribute7": "AR",
            "SKUAttribute8": "BZ",
            "SKUAttribute9": "CORE",
            "SKUAttribute10": "ZERO CALORIE",
            "c11": "Garment",
            "c12": "",
            "c13": "",
            "SKUAttribute14": "",
            "c15": "",
            "SkuLocAttribute1": "AREB5093",
            "SkuLocAttribute2": "40",
            "sl3": "AR",
            "sl4": "BZ",
            "sl5": "",
            "sl6": "",
            "sl7": "",
            "sl8": "",
            "sl9": "",
            "sl10": "AREB50934189",
            "sl11": "Yes",
            "sl12": "Jan-23",
            "sl13": "",
            "sl14": "",
            "sl15": "",
            "LocAttribute1": "EBO",
            "LocAttribute2": "10 to 15",
            "l3": "UP/UK",
            "l4": "D-2",
            "l5": "NEW OPENED",
            "l6": "NORTH",
            "l7": "Uttar Pradesh",
            "l8": "Agra",
            "l9": "EC",
            "l10": "",
            "l11": "",
            "l12": "",
            "l13": "",
            "l14": "",
            "l15": ""
        },
        {
            "RN": 46,
            "SKUCode": "AREB5093421",
            "SKUName": "SB2-NOTCH-KNIT-ZERO CALORIE-CORE",
            "LocCode": "4238",
            "LocName": "Sec11|Dwarka",
            "OldNormValue": 2,
            "NewNormValue": 1,
            "Type": 11,
            "Comment": "Norm 2 Consumption based Decrease",
            "PWhCode": "9020_EBO",
            "SKUAttribute1": "AREB5093",
            "SKUAttribute2": "42",
            "c3": "8.91E+12",
            "c4": "PC",
            "c5": "4999",
            "SKUAttribute6": "Arrow",
            "SKUAttribute7": "AR",
            "SKUAttribute8": "BZ",
            "SKUAttribute9": "CORE",
            "SKUAttribute10": "ZERO CALORIE",
            "c11": "Garment",
            "c12": "",
            "c13": "",
            "SKUAttribute14": "",
            "c15": "",
            "SkuLocAttribute1": "AREB5093",
            "SkuLocAttribute2": "42",
            "sl3": "AR",
            "sl4": "BZ",
            "sl5": "",
            "sl6": "",
            "sl7": "",
            "sl8": "",
            "sl9": "",
            "sl10": "AREB50934238",
            "sl11": "Yes",
            "sl12": "Nov-22",
            "sl13": "",
            "sl14": "",
            "sl15": "",
            "LocAttribute1": "EBO",
            "LocAttribute2": "10 to 15",
            "l3": "NCR",
            "l4": "D-2",
            "l5": "New",
            "l6": "North",
            "l7": "New Delhi",
            "l8": "New Delhi",
            "l9": "EC",
            "l10": "Yes",
            "l11": "",
            "l12": "",
            "l13": "",
            "l14": "",
            "l15": ""
        }
    ],
    "status": 200,
    "msg": null,
    "errorCount": null,
    "error": null,
    "conflictErrorCount": null,
    "conflictError": null
}

export const mockDBMUIConfigData : any={

    "recordCount": null,
    "data": [
        {
            "ReportName": "NormSuggestion",
            "Col_Code": "SKUAttribute1",
            "Col_Position": 99,
            "Header": "STYLE",
            "Visible": true,
            "CellAlignment": "left      ",
            "Value": "*Error*"
        },
        {
            "ReportName": "NormSuggestion",
            "Col_Code": "SKUAttribute2",
            "Col_Position": 99,
            "Header": "SIZE",
            "Visible": true,
            "CellAlignment": "left      ",
            "Value": "*Error*"
        },
        {
            "ReportName": "NormSuggestion",
            "Col_Code": "SKUAttribute6",
            "Col_Position": 99,
            "Header": "BRAND",
            "Visible": true,
            "CellAlignment": "left      ",
            "Value": "*Error"
        },
        {
            "ReportName": "NormSuggestion",
            "Col_Code": "SKUAttribute7",
            "Col_Position": 99,
            "Header": "SUB BRAND",
            "Visible": true,
            "CellAlignment": "left      ",
            "Value": "*Error"
        },
        {
            "ReportName": "NormSuggestion",
            "Col_Code": "SKUAttribute8",
            "Col_Position": 99,
            "Header": "CATEGORY",
            "Visible": true,
            "CellAlignment": "left      ",
            "Value": "*Error"
        },
        {
            "ReportName": "NormSuggestion",
            "Col_Code": "SKUAttribute9",
            "Col_Position": 99,
            "Header": "SEASON",
            "Visible": true,
            "CellAlignment": "left      ",
            "Value": "*Error"
        },
        {
            "ReportName": "NormSuggestion",
            "Col_Code": "SKUAttribute10",
            "Col_Position": 99,
            "Header": "Programme",
            "Visible": true,
            "CellAlignment": "left      ",
            "Value": "*Error"
        },
        {
            "ReportName": "NormSuggestion",
            "Col_Code": "SKUAttribute14",
            "Col_Position": 99,
            "Header": "Colour",
            "Visible": true,
            "CellAlignment": "left      ",
            "Value": "*Error"
        },
        {
            "ReportName": "NormSuggestion",
            "Col_Code": "LocAttribute1",
            "Col_Position": 99,
            "Header": "CHANNEL",
            "Visible": true,
            "CellAlignment": "left      ",
            "Value": "*Error*"
        },
        {
            "ReportName": "NormSuggestion",
            "Col_Code": "LocAttribute2",
            "Col_Position": 99,
            "Header": "STORE CLUSTER",
            "Visible": true,
            "CellAlignment": "left      ",
            "Value": "*Error*"
        },
        {
            "ReportName": "NormSuggestion",
            "Col_Code": "SKULocAttribute1",
            "Col_Position": 99,
            "Header": "sl1",
            "Visible": true,
            "CellAlignment": "left      ",
            "Value": "*Error*"
        },
        {
            "ReportName": "NormSuggestion",
            "Col_Code": "SKULocAttribute2",
            "Col_Position": 99,
            "Header": "sl2",
            "Visible": true,
            "CellAlignment": "left      ",
            "Value": "*Error*"
        },
        {
            "ReportName": "NormSuggestion",
            "Col_Code": "SKUCode",
            "Col_Position": 2,
            "Header": "SKU Code",
            "Visible": true,
            "CellAlignment": "left      ",
            "Value": "*Error*"
        },
        {
            "ReportName": "NormSuggestion",
            "Col_Code": "SKUName",
            "Col_Position": 3,
            "Header": "SKU Name",
            "Visible": true,
            "CellAlignment": "left      ",
            "Value": "*Error*"
        },
        {
            "ReportName": "NormSuggestion",
            "Col_Code": "LocCode",
            "Col_Position": 4,
            "Header": "Location Code",
            "Visible": true,
            "CellAlignment": "left      ",
            "Value": "*Error*"
        },
        {
            "ReportName": "NormSuggestion",
            "Col_Code": "LocName",
            "Col_Position": 5,
            "Header": "Location Name",
            "Visible": true,
            "CellAlignment": "left      ",
            "Value": "*Error*"
        }
    ],
    "status": 200,
    "msg": null,
    "errorCount": null,
    "error": null,
    "conflictErrorCount": null,
    "conflictError": null

}

export const mockDBMCountData : any={

    "recordCount": "25641",
    "data": null,
    "status": 200,
    "msg": null,
    "errorCount": null,
    "error": null,
    "conflictErrorCount": null,
    "conflictError": null
}

export const mockDBMApplySelectedNorm : any={

    "recordCount": null,
    "data": "",
    "status": 200,
    "msg": "Saved Succesfully",
    "errorCount": null,
    "error": null,
    "conflictErrorCount": null,
    "conflictError": null
}

export const mockDBMUpdateSleepTbl : any={

    "recordCount": null,
    "data": null,
    "status": 200,
    "msg": "Saved Succesfully",
    "errorCount": null,
    "error": null,
    "conflictErrorCount": null,
    "conflictError": null
}
