export enum UIColumnConfigName{
    GIT_From_Parent = "GIT_From_Parent",
    GIT_To_Child = "GIT_To_Child",
    Expedite_From_Parent = "Expedite_From_Parent",
    Expedite_To_Child = "Expedite_To_Child",
    Excess_Inventory_Review = "Excess_Inventory_Review",
    Order_Fulfillment_Review = "Order_Fulfillment_Review",
    BPR = "AdminBPR",
    BOR="BuyerOrderReport",
    BOR_OA = "BOR_OA",
    RRR = "RationRequirementReport",
    RRR_OA = "RRR_OA",
    Research_Insights = "ResearchInsight",
    DBM = "NormSuggestion",
    ChronicUnavailability = "ChronicUnavailability",
    OER = "OpenExpeditingRequests",
    OAR = "OrderAllocationReport",
    TRR = "RRR_OA",
    InTransit = "InTransitWhereAbouts",
    BuffertrendReport = "BuffertrendReport"
}

export enum UserUIColumnConfigName{
    GIT_From_Parent = "GIT_From_Parent",
    GIT_To_Child = "GIT_To_Child",
    Expedite_From_Parent = "Expedite_From_Parent",
    Expedite_To_Child = "Expedite_To_Child",
    Excess_Inventory_Review = "Excess_Inventory_Review",
    Order_Fulfillment_Review = "Order_Fulfillment_Review",
    BPR = "BPR",
    BOR = "BOR",
    BOR_OA = "BORColorBandwise",
    RRR = "RRR",
    RRR_OA = "RRRColorBandWise",
    Research_Insights = "ResearchInsight",
    DBM = "DBMNorm",
    ChronicUnavailability = "ChronicUnavailability",
    OER = "OpenExpeditingRequests",
    OAR = "OrderAllocationReport",
    TRR = "RRRColorBandWise",
    InTransit = "InTransitWhereAbouts",
    BTROnHand = "BTRon-hand",
    BTRPipeline = "BTRpipeline"
}