export const APIMock = [
    {
        tags: 1,
        bpp: 100,
        plnt: "Plant1",
        order_id: "ORD001",
        order_type: "Type1",
        lineitmid: "LITM001",
        item_code: "ITEM001",
        item_desc: "Item Description 1",
        oq: 100,
        dept1_time: "2h 30m",
        dept2_time: "3h 15m",
        dept3_time: "1h 45m",
        dept4_time: "2h 10m",
        lead_time: 7,
        due_dt: "2024-08-15",
        cus_code: "CUST001",
        cus_name: "Customer One"
    },
    {
        tags: 2,
        bpp: 100,
        plnt: "Plant2",
        order_id: "ORD002",
        order_type: "Type2",
        lineitmid: "LITM002",
        item_code: "ITEM002",
        item_desc: "Item Description 2",
        oq: 150,
        dept1_time: "3h 0m",
        dept2_time: "4h 0m",
        dept3_time: "2h 0m",
        dept4_time: "3h 0m",
        lead_time: 10,
        due_dt: "2024-08-20",
        cus_code: "CUST002",
        cus_name: "Customer Two"
    },
    {
        tags: 3,
        bpp: 100,
        plnt: "Plant3",
        order_id: "ORD003",
        order_type: "Type3",
        lineitmid: "LITM003",
        item_code: "ITEM003",
        item_desc: "Item Description 3",
        oq: 200,
        dept1_time: "4h 30m",
        dept2_time: "5h 0m",
        dept3_time: "3h 15m",
        dept4_time: "4h 0m",
        lead_time: 12,
        due_dt: "2024-08-25",
        cus_code: "CUST003",
        cus_name: "Customer Three"
    },
    {
        tags: 1,
        bpp: 100,
        plnt: "Plant4",
        order_id: "ORD004",
        order_type: "Type4",
        lineitmid: "LITM004",
        item_code: "ITEM004",
        item_desc: "Item Description 4",
        oq: 250,
        dept1_time: "5h 15m",
        dept2_time: "6h 30m",
        dept3_time: "4h 0m",
        dept4_time: "5h 0m",
        lead_time: 15,
        due_dt: "2024-08-30",
        cus_code: "CUST004",
        cus_name: "Customer Four"
    },
    {
        tags: 2,
        bpp: 100,
        plnt: "Plant5",
        order_id: "ORD005",
        order_type: "Type5",
        lineitmid: "LITM005",
        item_code: "ITEM005",
        item_desc: "Item Description 5",
        oq: 300,
        dept1_time: "6h 0m",
        dept2_time: "7h 0m",
        dept3_time: "5h 0m",
        dept4_time: "6h 0m",
        lead_time: 18,
        due_dt: "2024-09-05",
        cus_code: "CUST005",
        cus_name: "Customer Five"
    }
];



export const gridColumnConfig = [
    {
        cc: "tags",
        cp: 0,
        hd: "Tags",
        v: true,
        cla: "center",
        scc: "tags"
    },
    {
        cc: "bpp",
        cp: 1,
        hd: "BPP",
        v: true,
        cla: "center",
        scc: "bpp",
    },
    {
        cc: "plnt",
        cp: 2,
        hd: "Plant",
        v: true,
        cla: "center",
        scc: "plnt",
    },
    {
        cc: "order_id",
        cp: 3,
        hd: "Order Id",
        v: true,
        cla: "center",
        scc: "order_id",
    },
    {
        cc: "order_type",
        cp: 4,
        hd: "Order Type",
        v: true,
        cla: "center",
        scc: "order_type",
    },
    {
        cc: "lineitmid",
        cp: 5,
        hd: "Line Item ID",
        v: true,
        cla: "center",
        scc: "lineitmid",
    },
    {
        cc: "item_code",
        cp: 6,
        hd: "Item Code",
        v: true,
        cla: "center",
        scc: "item_code",
    },
    {
        cc: "item_desc",
        cp: 7,
        hd: "Item Description",
        v: true,
        cla: "center",
        scc: "item_desc",
    },
    {
        cc: "oq",
        cp: 8,
        hd: "Order Quantity",
        v: true,
        cla: "center",
        scc: "oq",
    },
    {
        cc: "dept1_time",
        cp: 9,
        hd: "Department 1 (Elapsed Time)",
        v: true,
        cla: "center",
        scc: "dept1_time",
    },
    {
        cc: "dept2_time",
        cp: 10,
        hd: "Department 2 (Elapsed Time)",
        v: true,
        cla: "center",
        scc: "dept2_time",
    },
    {
        cc: "dept3_time",
        cp: 11,
        hd: "Department 3 (Elapsed Time)",
        v: true,
        cla: "center",
        scc: "dept3_time",
    },
    {
        cc: "dept4_time",
        cp: 12,
        hd: "Department 4 (Elapsed Time)",
        v: true,
        cla: "center",
        scc: "dept4_time",
    },
    {
        cc: "lead_time",
        cp: 13,
        hd: "Lead Time (in Days)",
        v: true,
        cla: "center",
        scc: "lead_time",
    },
    {
        cc: "due_dt",
        cp: 14,
        hd: "Due Date",
        v: true,
        cla: "center",
        scc: "due_dt",
    },
    {
        cc: "cus_code",
        cp: 15,
        hd: "Customer Code",
        v: true,
        cla: "center",
        scc: "cus_code",
    },
    {
        cc: "cus_name",
        cp: 16,
        hd: "Customer Name",
        v: true,
        cla: "center",
        scc: "cus_name",
    },
];
