export const fullKitAssignmentData = {
  data: [
    {
      cl: "Black",
      pdd: "01-Jan-2023",
      oid: "ORD123",
      batch_no: "BATCH001",
      itemt: "SFG001",
      formul: "Formulation A",
      gen_name: "Generic Name A",
      batch_sz: "100",
      rn: "Route 1",
      cedd: "15-Jan-2023",
      bpp: 85,
    },
    {
      cl: "Black",
      pdd: "02-Feb-2023",
      oid: "ORD124",
      batch_no: "BATCH002",
      itemt: "SFG002",
      formul: "Formulation B",
      gen_name: "Generic Name B",
      batch_sz: "200",
      rn: "Route 2",
      cedd: "16-Feb-2023",
      bpp: 90,
    },
    {
      cl: "Red",
      pdd: "03-Mar-2023",
      oid: "ORD125",
      batch_no: "BATCH003",
      itemt: "SFG003",
      formul: "Formulation C",
      gen_name: "Generic Name C",
      batch_sz: "300",
      rn: "Route 3",
      cedd: "17-Mar-2023",
      bpp: 95,
    },
    {
      cl: "Red",
      pdd: "04-Apr-2023",
      oid: "ORD126",
      batch_no: "BATCH004",
      itemt: "SFG004",
      formul: "Formulation D",
      gen_name: "Generic Name D",
      batch_sz: "400",
      rn: "Route 4",
      cedd: "18-Apr-2023",
      bpp: 82,
    },
    {
      cl: "Red",
      pdd: "05-May-2023",
      oid: "ORD127",
      batch_no: "BATCH005",
      itemt: "SFG005",
      formul: "Formulation E",
      gen_name: "Generic Name E",
      batch_sz: "500",
      rn: "Route 5",
      cedd: "19-May-2023",
      bpp: 88,
    },
    {
      cl: "Yellow",
      pdd: "06-Jun-2023",
      oid: "ORD128",
      batch_no: "BATCH006",
      itemt: "SFG006",
      formul: "Formulation F",
      gen_name: "Generic Name F",
      batch_sz: "600",
      rn: "Route 6",
      cedd: "20-Jun-2023",
      bpp: 93,
    },
    {
      cl: "Green",
      pdd: "07-Jul-2023",
      oid: "ORD129",
      batch_no: "BATCH007",
      itemt: "SFG007",
      formul: "Formulation G",
      gen_name: "Generic Name G",
      batch_sz: "700",
      rn: "Route 7",
      cedd: "21-Jul-2023",
      bpp: 87,
    },
    {
      cl: "Green",
      pdd: "08-Aug-2023",
      oid: "ORD130",
      batch_no: "BATCH008",
      itemt: "SFG008",
      formul: "Formulation H",
      gen_name: "Generic Name H",
      batch_sz: "800",
      rn: "Route 8",
      cedd: "22-Aug-2023",
      bpp: 92,
    },
    {
      cl: "Green",
      pdd: "09-Sep-2023",
      oid: "ORD131",
      batch_no: "BATCH009",
      itemt: "SFG009",
      formul: "Formulation I",
      gen_name: "Generic Name I",
      batch_sz: "900",
      rn: "Route 9",
      cedd: "23-Sep-2023",
      bpp: 86,
    },
  ],
};


export const fullKitAssignmentHeader = {
  data: [
    {
      cc: "Action",
      cp: 1,
      hd: "Action",
      v: true,
      cla: "center",
      scc: "act",
    },
    {
      cc: "BufferType",
      cp: 1,
      hd: "Buffer Type",
      v: true,
      cla: "center",
      scc: "cl",
    },
    {
      cc: "ReleaseDate",
      cp: 2,
      hd: "Release Date",
      v: true,
      cla: "center",
      scc: "pdd",
    },
    {
      cc: "OrderNo",
      cp: 3,
      hd: "Order No",
      v: true,
      cla: "center",
      scc: "oid",
    },
    {
      cc: "BatchNo",
      cp: 4,
      hd: "Batch No",
      v: true,
      cla: "center",
      scc: "batch_no",
    },
    {
      cc: "SFGCode",
      cp: 5,
      hd: "SFG code",
      v: true,
      cla: "center",
      scc: "itemt",
    },
    {
      cc: "Formulation",
      cp: 6,
      hd: "Formulation",
      v: true,
      cla: "center",
      scc: "formul",
    },
    {
      cc: "GenericName",
      cp: 7,
      hd: "Generic Name",
      v: true,
      cla: "center",
      scc: "gen_name",
    },
    {
      cc: "BatchSize",
      cp: 8,
      hd: "Batch Size",
      v: true,
      cla: "center",
      scc: "batch_sz",
    },
    {
      cc: "Route",
      cp: 9,
      hd: "Route",
      v: true,
      cla: "center",
      scc: "rn",
    },
    {
      cc: "TargetSODispatchedDate",
      cp: 10,
      hd: "Target SO Dispatched Date",
      v: true,
      cla: "center",
      scc: "cedd",
    },
    {
      cc: "BPP",
      cp: 11,
      hd: "BPP",
      v: true,
      cla: "center",
      scc: "bpp",
    }
  ],
};
