export const fullKitAssignmentData = {
  data: [
    {
      bt: "Black",
      rd: "01-Jan-2023",
      ord_no: "ORD123",
      batch_no: "BATCH001",
      sfg_code: "SFG001",
      formul: "Formulation A",
      gen_name: "Generic Name A",
      batch_sz: "100",
      r: "Route 1",
      SO_dd: "15-Jan-2023",
      bpp: 85,
    },
    {
      bt: "Red",
      rd: "02-Feb-2023",
      ord_no: "ORD124",
      batch_no: "BATCH002",
      sfg_code: "SFG002",
      formul: "Formulation B",
      gen_name: "Generic Name B",
      batch_sz: "200",
      r: "Route 2",
      SO_dd: "16-Feb-2023",
      bpp: 90,
    },
    {
      bt: "Yellow",
      rd: "03-Mar-2023",
      ord_no: "ORD125",
      batch_no: "BATCH003",
      sfg_code: "SFG003",
      formul: "Formulation C",
      gen_name: "Generic Name C",
      batch_sz: "300",
      r: "Route 3",
      SO_dd: "17-Mar-2023",
      bpp: 95,
    },
    {
      bt: "Black",
      rd: "04-Apr-2023",
      ord_no: "ORD126",
      batch_no: "BATCH004",
      sfg_code: "SFG004",
      formul: "Formulation D",
      gen_name: "Generic Name D",
      batch_sz: "400",
      r: "Route 4",
      SO_dd: "18-Apr-2023",
      bpp: 82,
    },
    {
      bt: "Red",
      rd: "05-May-2023",
      ord_no: "ORD127",
      batch_no: "BATCH005",
      sfg_code: "SFG005",
      formul: "Formulation E",
      gen_name: "Generic Name E",
      batch_sz: "500",
      r: "Route 5",
      SO_dd: "19-May-2023",
      bpp: 88,
    },
    {
      bt: "Yellow",
      rd: "06-Jun-2023",
      ord_no: "ORD128",
      batch_no: "BATCH006",
      sfg_code: "SFG006",
      formul: "Formulation F",
      gen_name: "Generic Name F",
      batch_sz: "600",
      r: "Route 6",
      SO_dd: "20-Jun-2023",
      bpp: 93,
    },
    {
      bt: "Black",
      rd: "07-Jul-2023",
      ord_no: "ORD129",
      batch_no: "BATCH007",
      sfg_code: "SFG007",
      formul: "Formulation G",
      gen_name: "Generic Name G",
      batch_sz: "700",
      r: "Route 7",
      SO_dd: "21-Jul-2023",
      bpp: 87,
    },
    {
      bt: "Red",
      rd: "08-Aug-2023",
      ord_no: "ORD130",
      batch_no: "BATCH008",
      sfg_code: "SFG008",
      formul: "Formulation H",
      gen_name: "Generic Name H",
      batch_sz: "800",
      r: "Route 8",
      SO_dd: "22-Aug-2023",
      bpp: 92,
    },
    {
      bt: "Yellow",
      rd: "09-Sep-2023",
      ord_no: "ORD131",
      batch_no: "BATCH009",
      sfg_code: "SFG009",
      formul: "Formulation I",
      gen_name: "Generic Name I",
      batch_sz: "900",
      r: "Route 9",
      SO_dd: "23-Sep-2023",
      bpp: 86,
    },
  ],
};


export const fullKitAssignmentHeader = {
  data: [
    {
      cc: "Action",
      cp: 1,
      hd: "Action",
      v: true,
      cla: "center",
      scc: "act",
    },
    {
      cc: "BufferType",
      cp: 1,
      hd: "Buffer Type",
      v: true,
      cla: "center",
      scc: "bt",
    },
    {
      cc: "ReleaseDate",
      cp: 2,
      hd: "Release Date",
      v: true,
      cla: "center",
      scc: "rd",
    },
    {
      cc: "OrderNo",
      cp: 3,
      hd: "Order No",
      v: true,
      cla: "center",
      scc: "ord_no",
    },
    {
      cc: "BatchNo",
      cp: 4,
      hd: "Batch No",
      v: true,
      cla: "center",
      scc: "batch_no",
    },
    {
      cc: "SFGCode",
      cp: 5,
      hd: "SFG code",
      v: true,
      cla: "center",
      scc: "sfg_code",
    },
    {
      cc: "Formulation",
      cp: 6,
      hd: "Formulation",
      v: true,
      cla: "center",
      scc: "formul",
    },
    {
      cc: "GenericName",
      cp: 7,
      hd: "Generic Name",
      v: true,
      cla: "center",
      scc: "gen_name",
    },
    {
      cc: "BatchSize",
      cp: 8,
      hd: "Batch Size",
      v: true,
      cla: "center",
      scc: "batch_sz",
    },
    {
      cc: "Route",
      cp: 9,
      hd: "Route",
      v: true,
      cla: "center",
      scc: "r",
    },
    {
      cc: "TargetSODispatchedDate",
      cp: 10,
      hd: "Target SO Dispatched Date",
      v: true,
      cla: "center",
      scc: "SO_dd",
    },
    {
      cc: "BPP",
      cp: 11,
      hd: "BPP",
      v: true,
      cla: "center",
      scc: "bpp",
    }
  ],
};
