export const fullKitAssignmentData: any = {
  data: [
    {
      t: "Overloaded",
      cp: "Black",
      r: "M1, M2",
      on: "BMN12321",
      oq: "66",
      bs: "13",
      kbs: "50",
      fka: "66",
      oifkt: 90,
      ic: "BMN12321",
      id: "BMN12321",
      odd: "23-Jul-2023",
      ord: "23-Jul-2023",
    },
    {
      t: "Overloaded",
      cp: "Black",
      r: "M1, M2",
      on: "BMN12321",
      oq: "66",
      bs: "13",
      kbs: "50",
      fka: "66",
      oifkt: 90,
      ic: "BMN12321",
      id: "BMN12321",
      odd: "23-Jul-2023",
      ord: "23-Jul-2023",
    },
    {
      t: "Overloaded",
      cp: "Black",
      r: "M1, M2",
      on: "BMN12321",
      oq: "66",
      bs: "13",
      kbs: "50",
      fka: "66",
      oifkt: 90,
      ic: "BMN12321",
      id: "BMN12321",
      odd: "23-Jul-2023",
      ord: "23-Jul-2023",
    },
    {
      t: "Underloaded",
      cp: "Black",
      r: "M1, M2, M3",
      on: "BMN12321",
      oq: "66",
      bs: "13",
      kbs: "50",
      fka: "66",
      oifkt: 90,
      ic: "BMN12321",
      id: "BMN12321",
      odd: "23-Jul-2023",
      ord: "23-Jul-2023",
    },
    {
      t: "Underloaded",
      cp: "Red",
      r: "M3, M4",
      on: "BMN12321",
      oq: "66",
      bs: "13",
      kbs: "50",
      fka: "66",
      oifkt: 90,
      ic: "BMN12321",
      id: "BMN12321",
      odd: "23-Jul-2023",
      ord: "23-Jul-2023",
    },
    {
      t: "Underloaded",
      cp: "Yellow",
      r: "M1, M2",
      on: "BMN12321",
      oq: "66",
      bs: "13",
      kbs: "50",
      fka: "66",
      oifkt: 90,
      ic: "BMN12321",
      id: "BMN12321",
      odd: "23-Jul-2023",
      ord: "23-Jul-2023",
    },
    {
      t: "Balanced",
      cp: "Yellow",
      r: "M1, M2, M5",
      on: "BMN12321",
      oq: "66",
      bs: "13",
      kbs: "50",
      fka: "66",
      oifkt: 90,
      ic: "BMN12321",
      id: "BMN12321",
      odd: "23-Jul-2023",
      ord: "23-Jul-2023",
    },
  ],
};

export const fullKitAssignmentHeader = {
  data: [
    {
      cc: "Tags",
      cp: 1,
      hd: "Tags",
      v: true,
      cla: "center",
      scc: "t",
    },
    {
      cc: "ColorPriority",
      cp: 1,
      hd: "Color Priority",
      v: true,
      cla: "center",
      scc: "cp",
    },
    {
      cc: "Route",
      cp: 2,
      hd: "Route",
      v: true,
      cla: "center",
      scc: "r",
    },
    {
      cc: "OrderNo",
      cp: 3,
      hd: "Order No",
      v: true,
      cla: "center",
      scc: "on",
    },
    {
      cc: "OrderQty",
      cp: 4,
      hd: "Order Qty",
      v: true,
      cla: "center",
      scc: "oq",
    },
    {
      cc: "BatchSize",
      cp: 5,
      hd: "Batch Size",
      v: true,
      cla: "center",
      scc: "bs",
    },
    {
      cc: "KitBeforeSm",
      cp: 6,
      hd: "Kit Before SM",
      v: true,
      cla: "center",
      scc: "kbs",
    },
    {
      cc: "FullKitsAvail",
      cp: 7,
      hd: "Full Kits Available",
      v: true,
      cla: "center",
      scc: "fka",
    },
    {
      cc: "OrderInFullKitToday",
      cp: 8,
      hd: "Order In Full Kit Today",
      v: true,
      cla: "center",
      scc: "oifkt",
    },
    {
      cc: "ItemCode",
      cp: 9,
      hd: "Item Code",
      v: true,
      cla: "center",
      scc: "ic",
    },
    {
      cc: "ItemDescription",
      cp: 10,
      hd: "Item Description",
      v: true,
      cla: "center",
      scc: "id",
    },
    {
      cc: "OrderDueDate",
      cp: 11,
      hd: "Order Due Date",
      v: true,
      cla: "center",
      scc: "odd",
    },
    {
      cc: "OrderReceiveDate",
      cp: 11,
      hd: "Order Receive Date",
      v: true,
      cla: "center",
      scc: "ord",
    },
  ],
};
