// export const stplMockData = [
//     {
//       ccr: "BL2+BL3-AllExcept2.1",
//       exceedDays: 20,
//       days: 0,
//       plnt: 'A',
//       dept: 'Production',
//       ccrGrp: 'Sewing',
//       ccr: 'Flat Lock',
//       r_wip: 10,
//       un_fk: 20,
//       limit: 14,
//     },
//     {
//       ccr: "SG2-Dom-Normal",
//       exceedDays: 22,
//       days: 0,
//       plnt: 'A',
//       dept: 'Production',
//       ccrGrp: 'Sewing',
//       ccr: 'Flat Lock',
//       r_wip: 10,
//       un_fk: 20,
//       limit: 14,
//     },
//     {
//       ccr: "BL2+BL3-2.1",
//       exceedDays: 18,
//       days: 0,
//       plnt: 'A',
//       dept: 'Production',
//       ccrGrp: 'Sewing',
//       ccr: 'Flat Lock',
//       r_wip: 10,
//       un_fk: 20,
//       limit: 14,
//     },
//     {
//       ccr: "XYTable-Exp",
//       exceedDays: 0,
//       days: 10,
//       plnt: 'A',
//       dept: 'Production',
//       ccrGrp: 'Cutting',
//       ccr: 'Straight Knife',
//       r_wip: 20,
//       un_fk: 30,
//       limit: 11,
//     },
//     {
//       ccr: "XYTable-Dom-Normal",
//       exceedDays: 0,
//       days: 10,
//       plnt: 'A',
//       dept: 'Production',
//       ccrGrp: 'Cutting',
//       ccr: 'Straight Knife',
//       r_wip: 20,
//       un_fk: 30,
//       limit: 11,
//     },
//     {
//       ccr: "BL4",
//       exceedDays: 0,
//       days: 10,
//       plnt: 'A',
//       dept: 'Production',
//       ccrGrp: 'Cutting',
//       ccr: 'Straight Knife',
//       r_wip: 20,
//       un_fk: 30,
//       limit: 11,
//     },
//     {
//       ccr: "SG1-Dom-Normal",
//       exceedDays: 0,
//       days: 8,
//       plnt: 'A',
//       dept: 'Production',
//       ccrGrp: 'Cutting',
//       ccr: 'Straight Knife',
//       r_wip: 20,
//       un_fk: 30,
//       limit: 11,
//     },
//     {
//       ccr: "SG1-Exp-Normal",
//       exceedDays: 0,
//       days: 9,
//       plnt: 'A',
//       dept: 'Production',
//       ccrGrp: 'Cutting',
//       ccr: 'Straight Knife',
//       r_wip: 20,
//       un_fk: 30,
//       limit: 11,
//     },
//     {
//       ccr: "SG2-Exp-Normal",
//       exceedDays: 0,
//       days: 10,
//       plnt: 'A',
//       dept: 'Production',
//       ccrGrp: 'Sewing',
//       ccr: 'Flat Lock',
//       r_wip: 20,
//       un_fk: 30,
//       limit: 11,
//     },
// ]
// export const fullKitMockData = [
//     {
//       ccr: "BL2+BL3-AllExcept2.1",
//       exceedDays: 20,
//       days: 18,
//       plnt: 'A',
//       dept: 'Production',
//       ccrGrp: 'Sewing',
//       ccr: 'Flat Lock',
//       r_wip: 10,
//       un_fk: 20,
//       limit: 14,
//     },
//     {
//       ccr: "SG2-Dom-Normal",
//       exceedDays: 22,
//       days: 10,
//       plnt: 'A',
//       dept: 'Production',
//       ccrGrp: 'Sewing',
//       ccr: 'Flat Lock',
//       r_wip: 10,
//       un_fk: 20,
//       limit: 14,
//     },
//     {
//       ccr: "BL2+BL3-2.1",
//       exceedDays: 18,
//       days: 20,
//       plnt: 'A',
//       dept: 'Production',
//       ccrGrp: 'Sewing',
//       ccr: 'Flat Lock',
//       r_wip: 10,
//       un_fk: 20,
//       limit: 14,
//     },
//     {
//       ccr: "XYTable-Exp",
//       exceedDays: 0,
//       days: 10,
//       plnt: 'A',
//       dept: 'Production',
//       ccrGrp: 'Cutting',
//       ccr: 'Straight Knife',
//       r_wip: 20,
//       un_fk: 30,
//       limit: 11,
//     },
//     {
//       ccr: "XYTable-Dom-Normal",
//       exceedDays: 0,
//       days: 10,
//       plnt: 'A',
//       dept: 'Production',
//       ccrGrp: 'Cutting',
//       ccr: 'Straight Knife',
//       r_wip: 20,
//       un_fk: 30,
//       limit: 11,
//     },
//     {
//       ccr: "BL4",
//       exceedDays: 0,
//       days: 10,
//       plnt: 'A',
//       dept: 'Production',
//       ccrGrp: 'Cutting',
//       ccr: 'Straight Knife',
//       r_wip: 20,
//       un_fk: 30,
//       limit: 11,
//     },
//     {
//       ccr: "SG1-Dom-Normal",
//       exceedDays: 0,
//       days: 8,
//       plnt: 'A',
//       dept: 'Production',
//       ccrGrp: 'Cutting',
//       ccr: 'Straight Knife',
//       r_wip: 20,
//       un_fk: 30,
//       limit: 11,
//     },
//     {
//       ccr: "SG1-Exp-Normal",
//       exceedDays: 0,
//       days: 9,
//       plnt: 'A',
//       dept: 'Production',
//       ccrGrp: 'Cutting',
//       ccr: 'Straight Knife',
//       r_wip: 20,
//       un_fk: 30,
//       limit: 11,
//     },
//     {
//       ccr: "SG2-Exp-Normal",
//       exceedDays: 0,
//       days: 10,
//       plnt: 'A',
//       dept: 'Production',
//       ccrGrp: 'Sewing',
//       ccr: 'Flat Lock',
//       r_wip: 20,
//       un_fk: 30,
//       limit: 11,
//     },
// ]

export const APIMock = {
  stpl: [
    {
      ccr: "BL2+BL3-AllExcept2.1",
      exceedDays: 20,
      days: 0,
      limit: 14,
    },
    {
      ccr: "SG2-Dom-Normal",
      exceedDays: 22,
      days: 0,
      limit: 14,
    },
    {
      ccr: "BL2+BL3-2.1",
      exceedDays: 18,
      days: 0,
      limit: 14,
    },
    {
      ccr: "XYTable-Exp",
      exceedDays: 0,
      days: 10,
      limit: 11,
    },
    {
      ccr: "XYTable-Dom-Normal",
      exceedDays: 0,
      days: 10,
      limit: 11,
    },
    {
      ccr: "BL4",
      exceedDays: 0,
      days: 10,
      limit: 11,
    },
    {
      ccr: "SG1-Dom-Normal",
      exceedDays: 0,
      days: 8,
      limit: 11,
    },
    {
      ccr: "SG1-Exp-Normal",
      exceedDays: 0,
      days: 9,
      limit: 11,
    },
    {
      ccr: "SG2-Exp-Normal",
      exceedDays: 0,
      days: 10,
      limit: 11,
    },
  ],
  fullkit: [
    {
      ccr: "SG2-Dom-Normal",
      days: 10,
      limit: 14,
    },
    {
      ccr: "SG2-Dom-Normal",
      days: 10,
      limit: 14,
    },
    {
      ccr: "BL2+BL3-2.1",
      days: 12,
      limit: 14,
    },
    {
      ccr: "XYTable-Exp",
      days: 10,
      limit: 11,
    },
    {
      ccr: "XYTable-Dom-Normal",
      days: 10,
      limit: 11,
    },
    {
      ccr: "BL4",
      days: 10,
      limit: 11,
    },
    {
      ccr: "SG1-Dom-Normal",
      days: 8,
      limit: 11,
    },
    {
      ccr: "SG1-Exp-Normal",
      days: 9,
      limit: 11,
    },
    {
      ccr: "SG2-Exp-Normal",
      days: 10,
      limit: 11,
    },
  ],
  grid: [
    {
      plnt: "A",
      dept: "Production",
      ccrGrp: "Sewing",
      ccr: "Flat Lock",
      r_wip: 10,
      un_fk: 20,
      children: [
        {
          or_id: 873263,
          or_type: "End To End",
          line_item_id: 1,
          fg_code: "AKJDDIN",
          fg_desc: "FG Desc Text",
          order_quality: 100,
          quantity_manufacture: 50,
          r_wip: 10,
          fk: 20,
          un_fk: 0,
          children: [
            {
              rm_code: 65453,
              rm_desc: "ASGERSO",
              rm_req: 100,
              rm_avbl: 80,
              gap: 20,
            },
            {
              rm_code: 65453,
              rm_desc: "ASGERSO",
              rm_req: 100,
              rm_avbl: 80,
              gap: 20,
            },
            {
              rm_code: 65453,
              rm_desc: "ASGERSO",
              rm_req: 100,
              rm_avbl: 80,
              gap: 20,
            },
            {
              rm_code: 65453,
              rm_desc: "ASGERSO",
              rm_req: 100,
              rm_avbl: 80,
              gap: 20,
            },
            {
              rm_code: 65453,
              rm_desc: "ASGERSO",
              rm_req: 100,
              rm_avbl: 80,
              gap: 20,
            },
            {
              rm_code: 65453,
              rm_desc: "ASGERSO",
              rm_req: 100,
              rm_avbl: 80,
              gap: 20,
            },
          ],
        },
        {
          or_id: 873263,
          or_type: "End To End",
          line_item_id: 1,
          fg_code: "AKJDDIN",
          fg_desc: "FG Desc Text",
          order_quality: 100,
          quantity_manufacture: 50,
          r_wip: 10,
          fk: 70,
          un_fk: 0,
          children: [
            {
              rm_code: 65453,
              rm_desc: "ASGERSO",
              rm_req: 100,
              rm_avbl: 80,
              gap: 20,
            },
          ],
        },
        {
          or_id: 873263,
          or_type: "End To End",
          line_item_id: 1,
          fg_code: "AKJDDIN",
          fg_desc: "FG Desc Text",
          order_quality: 100,
          quantity_manufacture: 50,
          r_wip: 10,
          fk: 20,
          un_fk: 0,
          children: [
            {
              rm_code: 65453,
              rm_desc: "ASGERSO",
              rm_req: 100,
              rm_avbl: 80,
              gap: 20,
            },
          ],
        },
      ],
    },
    {
      plnt: "A",
      dept: "Production",
      ccrGrp: "Sewing",
      ccr: "Flat Lock",
      r_wip: 10,
      un_fk: 20,
      children: [
        {
            or_id: 873263,
            or_type: "End To End",
            line_item_id: 1,
            fg_code: "AKJDDIN",
            fg_desc: "FG Desc Text",
            order_quality: 100,
            quantity_manufacture: 50,
            r_wip: 10,
            fk: 25,
            un_fk: 0,
            children: [
              {
                rm_code: 65453,
                rm_desc: "ASGERSO",
                rm_req: 100,
                rm_avbl: 80,
                gap: 20,
              },
            ],
        },
      ],
    },
    {
      plnt: "A",
      dept: "Production",
      ccrGrp: "Sewing",
      ccr: "Flat Lock",
      r_wip: 10,
      un_fk: 20,
      children: [
        {
            or_id: 873263,
            or_type: "End To End",
            line_item_id: 1,
            fg_code: "AKJDDIN",
            fg_desc: "FG Desc Text",
            order_quality: 100,
            quantity_manufacture: 50,
            r_wip: 10,
            fk: 35,
            un_fk: 0,
            children: [
              {
                rm_code: 65453,
                rm_desc: "ASGERSO",
                rm_req: 100,
                rm_avbl: 80,
                gap: 20,
              },
            ],
        },
      ],
    },
    {
      plnt: "A",
      dept: "Production",
      ccrGrp: "Sewing",
      ccr: "Flat Lock",
      r_wip: 10,
      un_fk: 20,
      children: [
        {
            or_id: 873263,
            or_type: "End To End",
            line_item_id: 1,
            fg_code: "AKJDDIN",
            fg_desc: "FG Desc Text",
            order_quality: 100,
            quantity_manufacture: 50,
            r_wip: 10,
            fk: 30,
            un_fk: 0,
            children: [
              {
                rm_code: 65453,
                rm_desc: "ASGERSO",
                rm_req: 100,
                rm_avbl: 80,
                gap: 20,
              },
            ],
        },
        {
            or_id: 873263,
            or_type: "End To End",
            line_item_id: 1,
            fg_code: "AKJDDIN",
            fg_desc: "FG Desc Text",
            order_quality: 100,
            quantity_manufacture: 50,
            r_wip: 10,
            fk: 50,
            un_fk: 0,
            children: [
              {
                rm_code: 65453,
                rm_desc: "ASGERSO",
                rm_req: 100,
                rm_avbl: 80,
                gap: 20,
              },
            ],
        },
        {
            or_id: 873263,
            or_type: "End To End",
            line_item_id: 1,
            fg_code: "AKJDDIN",
            fg_desc: "FG Desc Text",
            order_quality: 100,
            quantity_manufacture: 50,
            r_wip: 10,
            fk: 20,
            un_fk: 0,
            children: [
              {
                rm_code: 65453,
                rm_desc: "ASGERSO",
                rm_req: 100,
                rm_avbl: 80,
                gap: 20,
              },
            ],
        },
      ],
    },
  ],
};
